// Mocks generated by Mockito 5.4.4 from annotations
// in libspiffy/test/beef_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:libspiffy/src/services/block_header_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spiffynode/src/chaincfg/hash.dart' as _i7;
import 'package:spiffynode/src/spv/chain_tip_tracker.dart' as _i2;
import 'package:spiffynode/src/wire/block_header.dart' as _i6;
import 'package:spiffynode/src/wire/messages/msg_headers.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChainTipTracker_0 extends _i1.SmartFake
    implements _i2.ChainTipTracker {
  _FakeChainTipTracker_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockHeaderServiceConfig_1 extends _i1.SmartFake
    implements _i3.BlockHeaderServiceConfig {
  _FakeBlockHeaderServiceConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BlockHeaderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockHeaderService extends _i1.Mock
    implements _i3.BlockHeaderService {
  MockBlockHeaderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChainTipTracker get chainTipTracker => (super.noSuchMethod(
        Invocation.getter(#chainTipTracker),
        returnValue: _FakeChainTipTracker_0(
          this,
          Invocation.getter(#chainTipTracker),
        ),
      ) as _i2.ChainTipTracker);

  @override
  _i3.BlockHeaderServiceConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeBlockHeaderServiceConfig_1(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.BlockHeaderServiceConfig);

  @override
  int get headerCount => (super.noSuchMethod(
        Invocation.getter(#headerCount),
        returnValue: 0,
      ) as int);

  @override
  int get chainHeight => (super.noSuchMethod(
        Invocation.getter(#chainHeight),
        returnValue: 0,
      ) as int);

  @override
  _i4.Stream<_i3.BlockHeaderEvent> get headerEvents => (super.noSuchMethod(
        Invocation.getter(#headerEvents),
        returnValue: _i4.Stream<_i3.BlockHeaderEvent>.empty(),
      ) as _i4.Stream<_i3.BlockHeaderEvent>);

  @override
  Map<String, dynamic> get statistics => (super.noSuchMethod(
        Invocation.getter(#statistics),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> processHeaders(
    _i5.MsgHeaders? headersMessage,
    String? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processHeaders,
          [
            headersMessage,
            peerId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String? getMerkleRoot(int? blockHeight) =>
      (super.noSuchMethod(Invocation.method(
        #getMerkleRoot,
        [blockHeight],
      )) as String?);

  @override
  _i6.BlockHeader? getHeader(int? blockHeight) =>
      (super.noSuchMethod(Invocation.method(
        #getHeader,
        [blockHeight],
      )) as _i6.BlockHeader?);

  @override
  _i6.BlockHeader? getHeaderByHash(_i7.Hash? blockHash) =>
      (super.noSuchMethod(Invocation.method(
        #getHeaderByHash,
        [blockHash],
      )) as _i6.BlockHeader?);

  @override
  List<_i6.BlockHeader> getHeadersInRange(
    int? startHeight,
    int? endHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeadersInRange,
          [
            startHeight,
            endHeight,
          ],
        ),
        returnValue: <_i6.BlockHeader>[],
      ) as List<_i6.BlockHeader>);

  @override
  bool validateHeaderChain(List<_i6.BlockHeader>? headers) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateHeaderChain,
          [headers],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasContinuousChain(int? toHeight) => (super.noSuchMethod(
        Invocation.method(
          #hasContinuousChain,
          [toHeight],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<int> getMissingHeights(
    int? startHeight,
    int? endHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMissingHeights,
          [
            startHeight,
            endHeight,
          ],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  void cleanupOrphanedHeaders() => super.noSuchMethod(
        Invocation.method(
          #cleanupOrphanedHeaders,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
