import 'dart:convert';
import 'package:dartsv/dartsv.dart' as dartsv;
import 'package:isar/isar.dart';
import 'package:libspiffy/src/storage/payment_channel_entity.dart';
import 'package:spiffynode/spiffy_node.dart';
import 'package:eventador/eventador.dart';
import 'package:duraq_isar/duraq_isar.dart' show IsarStorage;
import 'read_model_storage.dart';
import 'transaction_row_rules.dart';
import '../models/address_chain.dart';
import '../models/bitcoin_utxo.dart';
import '../models/bitcoin_transaction.dart';
import '../models/invoice_output_spec.dart';
import '../models/invoice_read_model.dart';
import '../actors/invoice_messages.dart' show InvoiceStatus;
part 'libspiffy_schemas.g.dart';

/// LibSpiffy's Isar schemas that developers can add to their Isar instance.
/// 
/// Usage:
/// ```dart
/// // After running: dart run build_runner build
/// final isar = await Isar.open([
///   ...LibSpiffySchemas.allSchemas,  // LibSpiffy + Eventador schemas
///   UserSchema,                      // Developer's own schemas
///   OrderSchema,
///   ProductSchema,
/// ]);
/// 
/// final walletStorage = IsarWalletStorage(isar);
/// ```
class LibSpiffySchemas {
  /// All wallet-related schemas for LibSpiffy (read models only)
  /// Note: These schemas are generated by Isar after running build_runner
  static List<CollectionSchema<dynamic>> get walletSchemas {
    // Generated schemas from build_runner
    return [
      BlockHeaderEntitySchema,
      MerkleProofEntitySchema,
      AncestorTransactionEntitySchema,
      PendingReceiveEntitySchema,
      DeferredPaymentEntitySchema,
      BitcoinUtxoEntitySchema,
      BitcoinTransactionEntitySchema,
      WalletMetadataEntitySchema,
      AddressEntitySchema,
      TransactionAddressEntitySchema,
      InvoiceEntitySchema,
      PaymentChannelEntitySchema,
    ];
  }
  
  /// All required schemas including event store and projections
  /// Use this when initializing LibSpiffy with full event sourcing support
  static List<CollectionSchema<dynamic>> get allSchemas {
    return [
      ...walletSchemas,
      ...IsarEventStore.allSchemas,
      ...IsarStorage.requiredSchemas,
    ];
  }
}

/// Block header storage entity for SPV validation
@collection
class BlockHeaderEntity {
  Id id = Isar.autoIncrement;

  /// Block height
  @Index()
  late int height;

  /// Block hash (hex string)
  @Index(unique: true)
  late String hash;

  /// Previous block hash
  late String prevBlockHash;

  /// Merkle root hash
  late String merkleRoot;

  /// Block timestamp (Unix timestamp)
  late int timestamp;

  /// Block version
  late int version;

  /// Difficulty bits
  late int bits;

  /// Block nonce
  late int nonce;

  /// Whether this header is orphaned due to reorganization
  @Index()
  late bool isOrphaned;

  /// When this header was stored
  late DateTime storedAt;

  BlockHeaderEntity();

  /// Create from SpiffyNode BlockHeader
  factory BlockHeaderEntity.fromBlockHeader(BlockHeader blockHeader, int height) {
    return BlockHeaderEntity()
      ..height = height
      ..hash = blockHeader.blockHash().toString()
      ..prevBlockHash = blockHeader.prevBlock.toString()
      ..merkleRoot = blockHeader.merkleRoot.toString()
      ..timestamp = blockHeader.timestamp.millisecondsSinceEpoch ~/ 1000
      ..version = blockHeader.version
      ..bits = blockHeader.bits
      ..nonce = blockHeader.nonce
      ..isOrphaned = false
      ..storedAt = DateTime.now();
  }

  /// Convert back to SpiffyNode BlockHeader
  /// Note: This reconstructs the BlockHeader from stored values
  BlockHeader toBlockHeader() {
    return BlockHeader(
      version: version,
      prevBlock: Hash.fromHex(prevBlockHash),
      merkleRoot: Hash.fromHex(merkleRoot),
      timestamp: DateTime.fromMillisecondsSinceEpoch(timestamp * 1000),
      bits: bits,
      nonce: nonce,
    );
  }

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'height': height,
      'hash': hash,
      'prevBlockHash': prevBlockHash,
      'merkleRoot': merkleRoot,
      'timestamp': timestamp,
      'version': version,
      'bits': bits,
      'nonce': nonce,
      'isOrphaned': isOrphaned,
      'storedAt': storedAt.toIso8601String(),
    };
  }

  /// Deserialize from JSON for restore
  factory BlockHeaderEntity.fromJson(Map<String, dynamic> json) {
    return BlockHeaderEntity()
      ..height = json['height'] as int
      ..hash = json['hash'] as String
      ..prevBlockHash = json['prevBlockHash'] as String
      ..merkleRoot = json['merkleRoot'] as String
      ..timestamp = json['timestamp'] as int
      ..version = json['version'] as int
      ..bits = json['bits'] as int
      ..nonce = json['nonce'] as int
      ..isOrphaned = json['isOrphaned'] as bool
      ..storedAt = DateTime.parse(json['storedAt'] as String);
  }
}

/// Merkle proof storage entity for SPV validation
@collection
class MerkleProofEntity {
  Id id = Isar.autoIncrement;

  /// Transaction ID this proof is for
  ///
  /// Rows are never deleted (bead mny): one row per (txid, block hash), and
  /// at most one current (verified or pendingHeader) row per txid. Both are enforced by
  /// [IsarWalletStorage.storeMerkleProof] rather than unique indexes: stores
  /// written before audit S-13 hold duplicates, and Isar refuses to open a
  /// collection whose new unique index the existing rows violate.
  @Index()
  late String txid;

  /// Block hash containing this transaction; null while its header is not
  /// known. Rows written before bead mny hold the placeholder 'pending'
  /// instead (read as null).
  @Index()
  String? blockHash;

  /// [MerkleProofStatus] name. Null on rows written before bead mny, which
  /// read as `pendingHeader` when [blockHash] is 'pending' and as `verified`
  /// otherwise.
  ///
  /// The composite (status, blockHeight) index serves the status queries
  /// (prefix) and the proofs of one status at the heights a reorganization
  /// changed, without reading every orphaned or rejected proof (bead
  /// libspiffy-hg0).
  @Index(composite: [CompositeIndex('blockHeight')])
  String? status;

  /// When [status] last changed.
  DateTime? statusChangedAt;

  /// Block height
  late int blockHeight;

  /// Position of transaction in block
  late int position;

  /// Merkle proof hashes (serialized as JSON)
  late String merkleProofJson;

  /// When this proof was stored
  late DateTime createdAt;

  MerkleProofEntity();

  /// Create from MerkleProof
  factory MerkleProofEntity.fromMerkleProof(MerkleProof proof) {
    return MerkleProofEntity()..setFrom(proof);
  }

  /// Overwrite every column but [id] with [proof].
  void setFrom(MerkleProof proof) {
    txid = proof.txid;
    blockHash = proof.blockHash == MerkleProof.legacyPendingBlockHash ? null : proof.blockHash;
    blockHeight = proof.blockHeight;
    position = proof.position;
    merkleProofJson = proof.merkleProof.join(',');
    createdAt = proof.createdAt;
    status = proof.status.name;
    statusChangedAt = proof.statusChangedAt;
  }

  /// Convert back to MerkleProof
  MerkleProof toMerkleProof() {
    final legacyPending = blockHash == MerkleProof.legacyPendingBlockHash;
    final stored = status;
    return MerkleProof(
      blockHash: legacyPending ? null : blockHash,
      txid: txid,
      // ''.split(',') is [''] — drop empty segments (audit S-13).
      merkleProof: merkleProofJson.split(',').where((s) => s.isNotEmpty).toList(),
      position: position,
      blockHeight: blockHeight,
      createdAt: createdAt,
      status: stored != null
          ? MerkleProofStatus.values.byName(stored)
          : (legacyPending ? MerkleProofStatus.pendingHeader : MerkleProofStatus.verified),
      statusChangedAt: statusChangedAt,
    );
  }

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'txid': txid,
      'blockHash': blockHash,
      'blockHeight': blockHeight,
      'position': position,
      'merkleProofJson': merkleProofJson,
      'createdAt': createdAt.toIso8601String(),
      'status': status,
      'statusChangedAt': statusChangedAt?.toIso8601String(),
    };
  }

  /// Deserialize from JSON for restore
  factory MerkleProofEntity.fromJson(Map<String, dynamic> json) {
    final changedAt = json['statusChangedAt'] as String?;
    return MerkleProofEntity()
      ..txid = json['txid'] as String
      ..blockHash = json['blockHash'] as String?
      ..blockHeight = json['blockHeight'] as int
      ..position = json['position'] as int
      ..merkleProofJson = json['merkleProofJson'] as String
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..status = json['status'] as String?
      ..statusChangedAt = changedAt == null ? null : DateTime.parse(changedAt);
  }
}

/// A transaction a received BEEF carried as an ancestor of the paid
/// transaction (bead libspiffy-zsh): SPV evidence needed to spend the
/// received outputs before they are mined, not a wallet transaction.
/// Keyed by txid only; rows are never deleted.
@collection
class AncestorTransactionEntity {
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String txid;

  /// The raw transaction.
  late String rawHex;

  /// When the row was first stored.
  late DateTime createdAt;

  AncestorTransactionEntity();
}

/// A receive parked until the block header(s) its merkle proof(s) need arrive
/// (bead libspiffy-vfai): the BEEF exactly as a counterparty handed it to us,
/// so the wallet is still credited when the header lands after a restart.
/// Keyed by (walletId, txid); rows are never deleted except with their wallet.
@collection
class PendingReceiveEntity {
  Id id = Isar.autoIncrement;

  /// The wallet the receive is for; empty when it names none.
  @Index(unique: true, replace: true, composite: [CompositeIndex('txid')])
  late String walletId;

  late String txid;

  /// The BEEF as received, hex encoded.
  late String beefHex;

  /// Who handed it to us.
  late String fromCounterparty;

  String? invoiceId;

  /// The highest block height a proof in the BEEF needs. The replay reads the
  /// waiting rows at or below the chain height through this index.
  @Index(composite: [CompositeIndex('neededHeight')])
  late bool waiting;

  late int neededHeight;

  late DateTime createdAt;

  late DateTime updatedAt;

  DateTime? resolvedAt;

  String? resolution;

  PendingReceiveEntity();

  factory PendingReceiveEntity.fromDomain(PendingReceive receive) => PendingReceiveEntity()
    ..walletId = receive.walletId
    ..txid = receive.txid
    ..beefHex = receive.beefHex
    ..fromCounterparty = receive.fromCounterparty
    ..invoiceId = receive.invoiceId
    ..waiting = receive.isWaiting
    ..neededHeight = receive.neededHeight
    ..createdAt = receive.createdAt
    ..updatedAt = receive.updatedAt
    ..resolvedAt = receive.resolvedAt
    ..resolution = receive.resolution;

  PendingReceive toDomain() => PendingReceive(
        walletId: walletId,
        txid: txid,
        beefHex: beefHex,
        fromCounterparty: fromCounterparty,
        invoiceId: invoiceId,
        neededHeight: neededHeight,
        createdAt: createdAt,
        updatedAt: updatedAt,
        resolvedAt: resolvedAt,
        resolution: resolution,
      );
}

/// A deferred payment (bead libspiffy-7p2): an outgoing transaction recorded
/// with a deferred spend, with the inputs it holds and its state. Rows are
/// never deleted except with their wallet.
@collection
class DeferredPaymentEntity {
  Id id = Isar.autoIncrement;

  /// (walletId, txid) is the key; (walletId, state, createdAt) serves the
  /// listing, so an outstanding-only query reads only outstanding rows.
  @Index(unique: true, replace: true, composite: [CompositeIndex('txid')])
  @Index(composite: [CompositeIndex('state'), CompositeIndex('createdAt')])
  late String walletId;

  late String txid;

  /// [DeferredPaymentState] name.
  late String state;

  late DateTime createdAt;
  late DateTime updatedAt;

  String? invoiceId;
  String? purpose;
  List<String> recipientAddresses = [];

  /// Decimal satoshis.
  late String amount;
  late String fee;

  /// JSON list of `{utxoKey, satoshis}`.
  late String heldInputsJson;

  String? lastNetworkStatus;
  String? lastNetworkStatusSource;
  DateTime? lastCheckedAt;
  DateTime? resolvedAt;
  String? resolutionReason;
  bool inferred = false;

  /// Competing txids ARC named (bead libspiffy-pkum); empty for a row stored
  /// before the property existed.
  List<String> competingTxids = [];

  DeferredPaymentEntity();

  factory DeferredPaymentEntity.fromDomain(DeferredPayment p) => DeferredPaymentEntity()
    ..walletId = p.walletId
    ..txid = p.txid
    ..state = p.state.name
    ..createdAt = p.createdAt
    ..updatedAt = p.updatedAt
    ..invoiceId = p.invoiceId
    ..purpose = p.purpose
    ..recipientAddresses = List<String>.from(p.recipientAddresses)
    ..amount = p.amount.toString()
    ..fee = p.fee.toString()
    ..heldInputsJson = p.heldInputsJson
    ..lastNetworkStatus = p.lastNetworkStatus
    ..lastNetworkStatusSource = p.lastNetworkStatusSource
    ..lastCheckedAt = p.lastCheckedAt
    ..resolvedAt = p.resolvedAt
    ..resolutionReason = p.resolutionReason
    ..inferred = p.inferred
    ..competingTxids = List<String>.from(p.competingTxids);

  DeferredPayment toDomain() => DeferredPayment(
        walletId: walletId,
        txid: txid,
        invoiceId: invoiceId,
        purpose: purpose,
        recipientAddresses: List<String>.from(recipientAddresses),
        amount: BigInt.tryParse(amount) ?? BigInt.zero,
        fee: BigInt.tryParse(fee) ?? BigInt.zero,
        heldInputs: DeferredPayment.heldInputsFromJson(heldInputsJson),
        state: DeferredPayment.stateFromName(state),
        lastNetworkStatus: lastNetworkStatus,
        lastNetworkStatusSource: lastNetworkStatusSource,
        lastCheckedAt: lastCheckedAt,
        createdAt: createdAt,
        updatedAt: updatedAt,
        resolvedAt: resolvedAt,
        resolutionReason: resolutionReason,
        inferred: inferred,
        competingTxids: List<String>.from(competingTxids),
      );
}

/// Bitcoin UTXO storage entity
@collection
class BitcoinUtxoEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this UTXO belongs to
  ///
  /// The composite (walletId, status) index lets the UTXO queries select a
  /// wallet's unspent or available rows without reading its spent ones
  /// (audit S-16). The composite (walletId, txid) index does the same for
  /// one transaction's outputs: the plain `txid` index below covers every
  /// wallet that holds an output of that transaction, so a lookup through it
  /// reads another wallet's rows (bead libspiffy-36jt).
  @Index()
  @Index(composite: [CompositeIndex('status')])
  @Index(composite: [CompositeIndex('txid')])
  late String walletId;

  /// Transaction ID
  @Index()
  late String txid;

  /// Output index
  late int vout;

  /// UTXO key (txid:vout)
  ///
  /// Unique per wallet, not globally (audit 2026-09-14 S-05): two wallets
  /// in one store can hold the same outpoint. Relaxing the former global
  /// unique index cannot fail on existing data when Isar rebuilds it.
  @Index(unique: true, composite: [CompositeIndex('walletId')])
  late String utxoKey;

  /// Value in satoshis (as string to handle BigInt)
  late String satoshis;

  /// Script public key (hex)
  late String scriptPubKey;

  /// Address (if derivable)
  String? address;

  /// Block height where this UTXO was created
  int? blockHeight;

  /// Number of confirmations
  late int confirmations;

  /// UTXO status ('available', 'reserved', 'spent')
  @Index()
  late String status;

  /// When this UTXO was created
  late DateTime createdAt;

  /// When this UTXO was last updated ([BitcoinUtxo.updatedAt]); null on
  /// rows written before it was stored (read back as [createdAt]).
  DateTime? updatedAt;

  /// When this UTXO was first stored as spent (if applicable). Part of the
  /// spend history: set once, never overwritten or cleared by an update.
  DateTime? spentAt;

  /// Transaction ID that spent this UTXO (if applicable)
  String? spentInTxId;

  /// Script type ('p2pkh', 'p2sh', 'multisig', etc.)
  late String scriptType;

  /// Whether the row's [status] is `available` — exactly
  /// [BitcoinUtxo.isAvailable], and nothing more.
  ///
  /// **Not `WalletBalances.isSpendable`**, which this was called until bead
  /// libspiffy-p8qc. That rule takes the whole wallet state — the watch
  /// addresses, the wallet's own addresses (for an output it cannot unlock
  /// alone), the deferred holds — so a per-row boolean cannot hold it and
  /// cannot stay correct: registering one watch address or deriving one key
  /// changes the answer for rows already written, and nothing rewrites
  /// them. The read side answers that question live, over the state it
  /// depends on (`splitBalanceUtxos`). The name promised the rule and
  /// stored the status, so the first query to filter on it would have
  /// selected plugin-managed, watch-only and cannot-unlock-alone outputs.
  late bool isAvailable;

  /// UTXO category ('funding', 'special', 'protocol')
  late String category;

  /// Plugin metadata as JSON string (null for standard P2PKH UTXOs)
  String? pluginMetadataJson;

  /// [BitcoinUtxo.derivationIndex]; null on rows written before it was
  /// stored.
  int? derivationIndex;

  /// The reservation of a reserved UTXO ([BitcoinUtxo.reservedByTxId],
  /// [BitcoinUtxo.reservationReason], [BitcoinUtxo.reservationExpiresAt],
  /// [BitcoinUtxo.reservationPriority]) and the status its release restores
  /// ([BitcoinUtxo.statusBeforeReservation], a [UTXOStatus] name). Null when
  /// not reserved, and on rows written before they were stored (bead
  /// libspiffy-viy).
  String? reservedByTxId;
  String? reservationReason;
  DateTime? reservationExpiresAt;
  int? reservationPriority;
  String? statusBeforeReservation;

  BitcoinUtxoEntity();

  /// Create from domain model BitcoinUtxo
  ///
  /// [walletId] is empty unless given; the storage sets it.
  factory BitcoinUtxoEntity.fromDomain(BitcoinUtxo utxo, {String walletId = ''}) {
    return BitcoinUtxoEntity()
      ..walletId = walletId
      ..txid = utxo.txid
      ..vout = utxo.vout
      ..utxoKey = '${utxo.txid}:${utxo.vout}'
      ..createdAt = utxo.createdAt
      ..scriptType = 'p2pkh' // Default, could be enhanced
      ..category = 'funding' // Default category
      ..applyDomain(utxo);
  }

  /// Copies the mutable state of [utxo] onto this row (the insert and the
  /// update path of the storage share it). A block height, plugin metadata
  /// or derivation index [utxo] lacks keeps the stored value; the spend
  /// history ([spentAt], [spentInTxId]) is only ever added to. The
  /// reservation fields follow [utxo] (a release clears them).
  void applyDomain(BitcoinUtxo utxo) {
    satoshis = utxo.satoshis.toString();
    scriptPubKey = utxo.scriptPubKey;
    address = utxo.address;
    // A zero-confirmation update (reorg, audit 3b0) clears the height.
    blockHeight = utxo.blockHeight ?? ((utxo.confirmations ?? 0) > 0 ? blockHeight : null);
    confirmations = utxo.confirmations ?? 0;
    status = utxo.status.name;
    updatedAt = utxo.updatedAt;
    if (utxo.status == UTXOStatus.spent) spentAt ??= utxo.updatedAt;
    isAvailable = utxo.status == UTXOStatus.available;
    if (utxo.pluginMetadata != null) {
      pluginMetadataJson = jsonEncode(utxo.pluginMetadata);
    }
    spentInTxId ??= utxo.spentInTxId;
    derivationIndex = utxo.derivationIndex ?? derivationIndex;
    reservedByTxId = utxo.reservedByTxId;
    reservationReason = utxo.reservationReason;
    reservationExpiresAt = utxo.reservationExpiresAt;
    reservationPriority = utxo.reservationPriority;
    statusBeforeReservation = utxo.statusBeforeReservation?.name;
  }

  /// Convert back to domain model BitcoinUtxo
  BitcoinUtxo toDomain() {
    // Parse status from stored string
    final utxoStatus = UTXOStatus.values.firstWhere(
      (s) => s.name == status,
      orElse: () => UTXOStatus.pending,  // Default fallback
    );
    
    // The stored timestamps, not "now" (audit S-20).
    return BitcoinUtxo(
      txid: txid,
      vout: vout,
      value: dartsv.Coin.ofSat(BigInt.parse(satoshis)),
      scriptPubKey: scriptPubKey,
      address: address ?? '',
      blockHeight: blockHeight,
      confirmations: confirmations,
      status: utxoStatus,
      createdAt: createdAt,
      updatedAt: updatedAt ?? createdAt,
      pluginMetadata: pluginMetadataJson != null
          ? Map<String, dynamic>.from(jsonDecode(pluginMetadataJson!) as Map)
          : null,
      derivationIndex: derivationIndex,
      reservedByTxId: reservedByTxId,
      reservationReason: reservationReason,
      reservationExpiresAt: reservationExpiresAt,
      reservationPriority: reservationPriority,
      statusBeforeReservation: UTXOStatus.values
          .where((s) => s.name == statusBeforeReservation)
          .firstOrNull,
      spentInTxId: spentInTxId,
    );
  }

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'walletId': walletId,
      'txid': txid,
      'vout': vout,
      'utxoKey': utxoKey,
      'satoshis': satoshis,
      'scriptPubKey': scriptPubKey,
      'address': address,
      'blockHeight': blockHeight,
      'confirmations': confirmations,
      'status': status,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'spentAt': spentAt?.toIso8601String(),
      'spentInTxId': spentInTxId,
      'scriptType': scriptType,
      'isAvailable': isAvailable,
      'category': category,
      'pluginMetadataJson': pluginMetadataJson,
      'derivationIndex': derivationIndex,
      'reservedByTxId': reservedByTxId,
      'reservationReason': reservationReason,
      'reservationExpiresAt': reservationExpiresAt?.toIso8601String(),
      'reservationPriority': reservationPriority,
      'statusBeforeReservation': statusBeforeReservation,
    };
  }

  /// Deserialize from JSON for restore
  factory BitcoinUtxoEntity.fromJson(Map<String, dynamic> json) {
    return BitcoinUtxoEntity()
      ..walletId = json['walletId'] as String
      ..txid = json['txid'] as String
      ..vout = json['vout'] as int
      ..utxoKey = json['utxoKey'] as String
      ..satoshis = json['satoshis'] as String
      ..scriptPubKey = json['scriptPubKey'] as String
      ..address = json['address'] as String?
      ..blockHeight = json['blockHeight'] as int?
      ..confirmations = json['confirmations'] as int
      ..status = json['status'] as String
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..updatedAt = json['updatedAt'] != null ? DateTime.parse(json['updatedAt'] as String) : null
      ..spentAt = json['spentAt'] != null ? DateTime.parse(json['spentAt'] as String) : null
      ..spentInTxId = json['spentInTxId'] as String?
      ..scriptType = json['scriptType'] as String
      // Backups written before bead libspiffy-p8qc carry the old key.
      ..isAvailable = (json['isAvailable'] ?? json['isSpendable']) as bool
      ..category = json['category'] as String
      ..pluginMetadataJson = json['pluginMetadataJson'] as String?
      ..derivationIndex = json['derivationIndex'] as int?
      ..reservedByTxId = json['reservedByTxId'] as String?
      ..reservationReason = json['reservationReason'] as String?
      ..reservationExpiresAt = json['reservationExpiresAt'] != null
          ? DateTime.parse(json['reservationExpiresAt'] as String)
          : null
      ..reservationPriority = json['reservationPriority'] as int?
      ..statusBeforeReservation = json['statusBeforeReservation'] as String?;
  }
}

/// Bitcoin transaction storage entity
@collection
class BitcoinTransactionEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this transaction belongs to
  ///
  /// The composite (walletId, createdAt) index serves the newest-first,
  /// paginated history query (audit S-16).
  @Index()
  @Index(composite: [CompositeIndex('createdAt')])
  late String walletId;

  /// Transaction ID
  ///
  /// Unique per wallet (audit 2026-09-14 S-05): when wallet A pays wallet B
  /// in the same store each wallet has its own row. The plain `txid` index
  /// serves wallet-independent lookups.
  @Index()
  @Index(unique: true, composite: [CompositeIndex('walletId')])
  late String txid;

  /// Raw transaction hex
  late String rawHex;

  /// Block height (null if unconfirmed)
  int? blockHeight;

  /// Block hash (null if unconfirmed)
  String? blockHash;

  /// Number of confirmations
  late int confirmations;

  /// Total input amount (as string to handle BigInt)
  late String totalInput;

  /// Total output amount (as string to handle BigInt)
  late String totalOutput;

  /// Transaction fee (as string to handle BigInt)
  late String fee;
  
  /// Net amount from wallet's perspective (as string to handle BigInt)
  /// Positive for incoming, negative for outgoing
  late String netAmount;

  /// Whether this is an incoming transaction
  late bool isIncoming;

  /// Whether this is an outgoing transaction
  late bool isOutgoing;

  /// Transaction status ('pending', 'confirmed', 'failed')
  ///
  /// The composite (status, walletId) index serves status queries across
  /// every wallet (prefix) and for one wallet, so a wallet's query does not
  /// read other wallets' rows (audit S-16). The composite (status,
  /// blockHeight) index serves the confirmed rows at or above a height (a
  /// header-chain reorganization) without reading the confirmed history
  /// (bead libspiffy-ctkm). The composite (status, updatedAt) index serves a
  /// bounded window of the rows with a status that changed recently (bead
  /// libspiffy-5bju: ARCActor polling recently failed transactions) without
  /// reading that status's whole history.
  @Index(composite: [CompositeIndex('walletId')])
  @Index(composite: [CompositeIndex('blockHeight')])
  @Index(composite: [CompositeIndex('updatedAt')])
  late String status;

  /// When this transaction was created/received
  @Index()
  late DateTime createdAt;

  /// When this row was last updated ([BitcoinTransaction.updatedAt]); null
  /// on rows written before it was stored (read back as [createdAt]).
  DateTime? updatedAt;

  /// When this transaction was confirmed (if applicable)
  DateTime? confirmedAt;

  /// When this transaction was broadcast
  DateTime? broadcastAt;

  /// Counterparty information (who sent/received)
  String? counterparty;

  /// Notes or metadata about this transaction
  String? notes;

  /// Receiving addresses (stored as JSON array string)
  late String receivingAddressesJson = '[]';

  /// Sending addresses (stored as JSON array string)
  late String sendingAddressesJson = '[]';

  /// Primary counterparty for quick filtering
  @Index()
  String? primaryCounterparty;

  /// The app's opaque marker for the counterparty this payment was with
  /// (bead libspiffy-cq16, spv-understanding.md "Core Data Management"
  /// requirement 5). Distinct from [counterparty] and
  /// [primaryCounterparty], which are derived from bitcoin ADDRESSES (v015):
  /// an address is not an identity. Set once, by the first record that
  /// carries one, and never blanked or replaced
  /// ([TransactionRowRules.counterpartyMarkerAfter]). Null on rows written
  /// before the field existed.
  String? counterpartyMarker;

  /// The transaction's `nLockTime` (bead libspiffy-zpu7). Null on rows
  /// written before the field existed; [toDomain] recovers those from
  /// [rawHex] where it is a transaction we can read, and leaves them null
  /// where it is not — a `0` here would say "spendable now" about a refund
  /// that is locked.
  int? lockTime;

  /// The transaction's version field (bead libspiffy-zpu7). Null on rows
  /// written before the field existed, recovered from [rawHex] on read as
  /// [lockTime] is.
  int? version;

  BitcoinTransactionEntity();

  /// Create from domain model BitcoinTransaction
  ///
  /// The single conversion used by the storage for a new row (audit S-21).
  /// [walletId] overrides [BitcoinTransaction.walletId] (empty when neither
  /// is given).
  factory BitcoinTransactionEntity.fromDomain(BitcoinTransaction tx, {String? walletId}) {
    return BitcoinTransactionEntity()
      ..walletId = walletId ?? tx.walletId ?? ''
      ..txid = tx.txid
      ..rawHex = tx.rawHex
      ..blockHash = null // Not available in BitcoinTransaction
      ..createdAt = tx.createdAt
      ..broadcastAt = null // Not available in BitcoinTransaction
      ..counterparty = primaryCounterpartyOf(tx)
      ..applyDomain(tx);
  }

  /// Copies the mutable state of [tx] onto this row (the insert and the
  /// update path of the storage share it). History is not erased: an empty
  /// raw hex or a null block height keeps the stored value (an SPV wallet
  /// cannot fetch the transaction again), `confirmedAt` is set once the
  /// transaction has a block height and is not cleared, and the counterparty
  /// marker is set once and never blanked or replaced (cq16).
  void applyDomain(BitcoinTransaction tx) {
    final net = tx.netAmount;
    if (tx.rawHex.isNotEmpty) rawHex = tx.rawHex;
    status = tx.status.name;
    // A non-confirmed update clears the height (reorg, audit 3b0).
    blockHeight = tx.blockHeight ?? (tx.status == TransactionStatus.confirmed ? blockHeight : null);
    confirmations = tx.confirmations ?? 0;
    totalInput = tx.inputValue.toString();
    totalOutput = tx.outputValue.toString();
    fee = tx.fee.toString();
    netAmount = net.toString();
    isIncoming = net > BigInt.zero;
    isOutgoing = net < BigInt.zero;
    receivingAddressesJson = jsonEncode(tx.receivingAddresses);
    sendingAddressesJson = jsonEncode(tx.sendingAddresses);
    primaryCounterparty = primaryCounterpartyOf(tx);
    // Set once, never blanked, never replaced (cq16).
    counterpartyMarker = TransactionRowRules.counterpartyMarkerAfter(counterpartyMarker, tx.counterpartyMarker);
    notes = tx.memo;
    // Consensus fields the txid commits to: set once, never blanked and
    // never revised by a later record (zpu7).
    final intrinsics = TransactionRowRules.intrinsicsOf(tx);
    lockTime = TransactionRowRules.intrinsicAfter(lockTime, intrinsics.lockTime);
    version = TransactionRowRules.intrinsicAfter(version, intrinsics.version);
    updatedAt = tx.updatedAt;
    if (tx.blockHeight != null && tx.blockHeight! > 0) {
      confirmedAt = tx.updatedAt;
    }
  }

  /// The other party of [tx] from the wallet's perspective: the first
  /// sending address of an incoming transaction, the first receiving
  /// address of an outgoing one, null otherwise.
  /// The rule every backend shares ([TransactionRowRules.primaryCounterpartyOf]).
  static String? primaryCounterpartyOf(BitcoinTransaction tx) => TransactionRowRules.primaryCounterpartyOf(tx);

  /// Convert back to domain model BitcoinTransaction
  BitcoinTransaction toDomain() {
    final receiving = receivingAddressesJson.isNotEmpty && receivingAddressesJson != '[]'
        ? (jsonDecode(receivingAddressesJson) as List).cast<String>()
        : <String>[];
    final sending = sendingAddressesJson.isNotEmpty && sendingAddressesJson != '[]'
        ? (jsonDecode(sendingAddressesJson) as List).cast<String>()
        : <String>[];
    final recovered = (lockTime == null || version == null)
        ? TransactionRowRules.intrinsicsOfRawHex(rawHex)
        : null;

    return BitcoinTransaction(
      walletId: walletId.isNotEmpty ? walletId : null,
      txid: txid,
      rawHex: rawHex,
      status: TransactionStatus.values.firstWhere((s) => s.name == status),
      blockHeight: blockHeight,
      confirmations: confirmations,
      inputValue: BigInt.parse(totalInput),
      outputValue: BigInt.parse(totalOutput),
      fee: BigInt.parse(fee),
      receivingAddresses: receiving,
      sendingAddresses: sending,
      netAmount: BigInt.parse(netAmount), // Read directly from stored value
      createdAt: createdAt,
      updatedAt: updatedAt ?? createdAt,
      memo: notes,
      // Rows written before the columns existed have neither; the raw hex
      // the wallet never drops still carries both (zpu7). Where it does not,
      // the reading stays absent rather than becoming a fabricated 0/1.
      lockTime: lockTime ?? recovered?.lockTime,
      version: version ?? recovered?.version,
      counterpartyMarker: counterpartyMarker,
    );
  }

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'walletId': walletId,
      'txid': txid,
      'rawHex': rawHex,
      'blockHeight': blockHeight,
      'blockHash': blockHash,
      'confirmations': confirmations,
      'totalInput': totalInput,
      'totalOutput': totalOutput,
      'fee': fee,
      'netAmount': netAmount,
      'isIncoming': isIncoming,
      'isOutgoing': isOutgoing,
      'status': status,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'confirmedAt': confirmedAt?.toIso8601String(),
      'broadcastAt': broadcastAt?.toIso8601String(),
      'counterparty': counterparty,
      'notes': notes,
      'receivingAddressesJson': receivingAddressesJson,
      'sendingAddressesJson': sendingAddressesJson,
      'primaryCounterparty': primaryCounterparty,
      'counterpartyMarker': counterpartyMarker,
      'lockTime': lockTime,
      'version': version,
    };
  }

  /// Deserialize from JSON for restore
  factory BitcoinTransactionEntity.fromJson(Map<String, dynamic> json) {
    return BitcoinTransactionEntity()
      ..walletId = json['walletId'] as String
      ..txid = json['txid'] as String
      ..rawHex = json['rawHex'] as String
      ..blockHeight = json['blockHeight'] as int?
      ..blockHash = json['blockHash'] as String?
      ..confirmations = json['confirmations'] as int
      ..totalInput = json['totalInput'] as String
      ..totalOutput = json['totalOutput'] as String
      ..fee = json['fee'] as String
      ..netAmount = json['netAmount'] as String
      ..isIncoming = json['isIncoming'] as bool
      ..isOutgoing = json['isOutgoing'] as bool
      ..status = json['status'] as String
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..updatedAt = json['updatedAt'] != null ? DateTime.parse(json['updatedAt'] as String) : null
      ..confirmedAt = json['confirmedAt'] != null ? DateTime.parse(json['confirmedAt'] as String) : null
      ..broadcastAt = json['broadcastAt'] != null ? DateTime.parse(json['broadcastAt'] as String) : null
      ..counterparty = json['counterparty'] as String?
      ..notes = json['notes'] as String?
      ..receivingAddressesJson = json['receivingAddressesJson'] as String
      ..sendingAddressesJson = json['sendingAddressesJson'] as String
      ..primaryCounterparty = json['primaryCounterparty'] as String?
      // Absent on backups written before each field existed (cq16, zpu7).
      ..counterpartyMarker = json['counterpartyMarker'] as String?
      ..lockTime = json['lockTime'] as int?
      ..version = json['version'] as int?;
  }
}

/// Wallet metadata storage entity
@collection
class WalletMetadataEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID
  @Index(unique: true)
  late String walletId;

  /// Wallet name
  late String name;

  /// Wallet type ('hd', 'single', 'multisig')
  late String walletType;

  /// Network ('mainnet', 'testnet', 'regtest')
  late String network;

  /// Root address (if applicable)
  String? rootAddress;

  /// Current derivation index for HD wallets
  late int derivationIndex;

  /// Whether the wallet is created/initialized
  late bool isCreated;

  /// Whether the wallet has been deleted (soft-delete for event replay safety)
  bool isDeleted = false;

  /// When this wallet was created
  late DateTime createdAt;

  /// Last time this wallet was accessed
  late DateTime lastAccessedAt;

  /// Wallet metadata (serialized as JSON)
  late String metadataJson;

  /// Current aggregate version
  late int aggregateVersion;

  /// Cached confirmed balance (as string to handle BigInt)
  late String confirmedBalance;

  /// Cached unconfirmed balance (as string to handle BigInt)
  late String unconfirmedBalance;

  /// List of wallet addresses (serialized as JSON)
  late String addressesJson;

  /// List of wallet public keys (serialized as JSON)
  late String publicKeysJson;

  WalletMetadataEntity();

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'walletId': walletId,
      'name': name,
      'walletType': walletType,
      'network': network,
      'rootAddress': rootAddress,
      'derivationIndex': derivationIndex,
      'isCreated': isCreated,
      'createdAt': createdAt.toIso8601String(),
      'lastAccessedAt': lastAccessedAt.toIso8601String(),
      'metadataJson': metadataJson,
      'aggregateVersion': aggregateVersion,
      'confirmedBalance': confirmedBalance,
      'unconfirmedBalance': unconfirmedBalance,
      'addressesJson': addressesJson,
      'publicKeysJson': publicKeysJson,
    };
  }

  /// Deserialize from JSON for restore
  factory WalletMetadataEntity.fromJson(Map<String, dynamic> json) {
    return WalletMetadataEntity()
      ..walletId = json['walletId'] as String
      ..name = json['name'] as String
      ..walletType = json['walletType'] as String
      ..network = json['network'] as String
      ..rootAddress = json['rootAddress'] as String?
      ..derivationIndex = json['derivationIndex'] as int
      ..isCreated = json['isCreated'] as bool
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..lastAccessedAt = DateTime.parse(json['lastAccessedAt'] as String)
      ..metadataJson = json['metadataJson'] as String
      ..aggregateVersion = json['aggregateVersion'] as int
      ..confirmedBalance = json['confirmedBalance'] as String
      ..unconfirmedBalance = json['unconfirmedBalance'] as String
      ..addressesJson = json['addressesJson'] as String
      ..publicKeysJson = json['publicKeysJson'] as String;
  }
}

/// Address entity for efficient address lookup and metadata
@collection
class AddressEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this address belongs to
  ///
  /// The composite (walletId, purpose) index serves every per-wallet address
  /// query (prefix) and the purpose lookup, so reading a wallet's watch
  /// addresses does not read its derived addresses (audit S-16).
  @Index(composite: [CompositeIndex('purpose')])
  late String walletId;

  /// Bitcoin address (base58) or payment destination identifier
  ///
  /// Unique per wallet (audit 2026-09-14 S-12): the same address may be
  /// registered by two wallets (for example a watch-only copy).
  @Index(type: IndexType.hash)
  @Index(unique: true, composite: [CompositeIndex('walletId')])
  late String address;

  /// Script type: 'p2pkh', 'p2pk', 'p2ms', 'p2sh', 'custom', 'unknown'
  late String scriptType;

  /// Derivation path (e.g., "m/44'/0'/0'/0/0")
  String? derivationPath;

  /// Derivation index (for quick range queries)
  @Index()
  int? derivationIndex;

  /// The address's chain, as [AddressChain.index]: the key is at
  /// m/{chain}/{derivationIndex}. Null in a row written before the delegated
  /// chain existed, whose chain [isChange] alone records.
  int? chain;

  /// Whether the address is on the change chain. Written with [chain] for
  /// every row, and the only chain record of a row written before [chain]
  /// existed; read it through [AddressChain.fromRecord], never on its own.
  late bool isChange;

  /// The payer's public key (compressed hex) of a type-42 address: one a
  /// payer derived from the wallet's anchor key (bead libspiffy-zxkd,
  /// `Type42Derivation`). Null for every other address; a type-42 row has no
  /// [chain] and no [derivationIndex].
  String? type42SenderPublicKey;

  /// The invoice number of a type-42 address, with [type42SenderPublicKey].
  String? type42InvoiceNumber;

  /// The anchor key (compressed hex) a type-42 address was derived from, and
  /// the context (hex) the wallet issued it for (bead libspiffy-fdal).
  String? type42AnchorPublicKey;
  String? type42AnchorContext;

  /// Address label (user-friendly name)
  String? label;

  /// Address purpose ('receive', 'change', 'invoice', 'import')
  late String purpose;

  /// First time this address was used (received funds)
  DateTime? firstUsedAt;

  /// Last time this address was used
  DateTime? lastUsedAt;

  /// Number of times this address has been used
  late int usageCount;

  /// Current balance (as string for BigInt)
  late String balance;

  /// When this address was generated/discovered
  late DateTime createdAt;

  /// Is this address currently being watched?
  late bool isWatched;

  AddressEntity();

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'walletId': walletId,
      'address': address,
      'scriptType': scriptType,
      'derivationPath': derivationPath,
      'derivationIndex': derivationIndex,
      'chain': chain,
      'isChange': isChange,
      'type42SenderPublicKey': type42SenderPublicKey,
      'type42InvoiceNumber': type42InvoiceNumber,
      'type42AnchorPublicKey': type42AnchorPublicKey,
      'type42AnchorContext': type42AnchorContext,
      'label': label,
      'purpose': purpose,
      'firstUsedAt': firstUsedAt?.toIso8601String(),
      'lastUsedAt': lastUsedAt?.toIso8601String(),
      'usageCount': usageCount,
      'balance': balance,
      'createdAt': createdAt.toIso8601String(),
      'isWatched': isWatched,
    };
  }

  /// Deserialize from JSON for restore
  factory AddressEntity.fromJson(Map<String, dynamic> json) {
    return AddressEntity()
      ..walletId = json['walletId'] as String
      ..address = json['address'] as String
      ..scriptType = json['scriptType'] as String
      ..derivationPath = json['derivationPath'] as String?
      ..derivationIndex = json['derivationIndex'] as int?
      ..chain = json['chain'] as int?
      ..isChange = json['isChange'] as bool
      ..type42SenderPublicKey = json['type42SenderPublicKey'] as String?
      ..type42InvoiceNumber = json['type42InvoiceNumber'] as String?
      ..type42AnchorPublicKey = json['type42AnchorPublicKey'] as String?
      ..type42AnchorContext = json['type42AnchorContext'] as String?
      ..label = json['label'] as String?
      ..purpose = json['purpose'] as String
      ..firstUsedAt = json['firstUsedAt'] != null ? DateTime.parse(json['firstUsedAt'] as String) : null
      ..lastUsedAt = json['lastUsedAt'] != null ? DateTime.parse(json['lastUsedAt'] as String) : null
      ..usageCount = json['usageCount'] as int
      ..balance = json['balance'] as String
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..isWatched = json['isWatched'] as bool;
  }
}

/// Junction table for transaction-address many-to-many relationship
/// Enables efficient queries like "all transactions involving address X"
@collection
class TransactionAddressEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID (for partition isolation)
  @Index()
  late String walletId;

  /// Transaction ID
  @Index()
  late String txid;

  /// Address involved in this transaction
  @Index()
  late String address;

  /// Direction: 'input' or 'output'
  @Index()
  late String direction;

  /// Amount in satoshis (as string for BigInt)
  late String amount;

  /// Output index (vout) if this is an output
  int? vout;

  /// Input index (vin) if this is an input
  int? vin;

  /// When this junction record was created
  late DateTime createdAt;

  /// Composite index for wallet+address queries
  @Index(composite: [CompositeIndex('address')])
  late String walletIdAddress;

  /// Composite index for wallet+txid queries
  @Index(composite: [CompositeIndex('txid')])
  late String walletIdTxid;

  TransactionAddressEntity();

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'walletId': walletId,
      'txid': txid,
      'address': address,
      'direction': direction,
      'amount': amount,
      'vout': vout,
      'vin': vin,
      'createdAt': createdAt.toIso8601String(),
      'walletIdAddress': walletIdAddress,
      'walletIdTxid': walletIdTxid,
    };
  }

  /// Deserialize from JSON for restore
  factory TransactionAddressEntity.fromJson(Map<String, dynamic> json) {
    return TransactionAddressEntity()
      ..walletId = json['walletId'] as String
      ..txid = json['txid'] as String
      ..address = json['address'] as String
      ..direction = json['direction'] as String
      ..amount = json['amount'] as String
      ..vout = json['vout'] as int?
      ..vin = json['vin'] as int?
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..walletIdAddress = json['walletIdAddress'] as String
      ..walletIdTxid = json['walletIdTxid'] as String;
  }
}

/// Invoice entity for payment request management
@collection
class InvoiceEntity {
  Id id = Isar.autoIncrement;

  /// Invoice identifier (UUID)
  @Index(unique: true)
  late String invoiceId;

  /// Wallet that owns this invoice
  @Index()
  late String walletId;

  /// Payment addresses for this invoice (serialized as JSON list)
  late String addressesJson;

  /// Amount expected in satoshis (stored as string to handle BigInt)
  late String amount;

  /// Optional description
  String? description;

  /// Invoice status (pending, paid, expired, cancelled)
  @Index()
  late String status;

  /// When the invoice was created
  @Index()
  late DateTime createdAt;

  /// When the invoice expires (null for no expiration)
  DateTime? expiresAt;

  /// When the invoice was paid (null if not paid)
  DateTime? paidAt;

  /// Transaction ID of payment (null if not paid)
  String? paymentTxid;

  /// Amount received in satoshis (stored as string to handle BigInt)
  String? amountReceived;

  /// Invoice metadata (serialized as JSON)
  String? metadataJson;

  /// Structured output specifications (serialized as JSON)
  /// Contains P2PKH and P2MS output specs for multi-output invoices
  String? outputsJson;

  InvoiceEntity();

  /// Create from the invoice read model the projection stores.
  factory InvoiceEntity.fromDomain(InvoiceReadModel invoice) {
    final outputs = invoice.outputs;
    return InvoiceEntity()
      ..invoiceId = invoice.invoiceId
      ..walletId = invoice.walletId
      ..addressesJson = _encodeList(invoice.addresses)
      ..amount = invoice.amount.toString()
      ..description = invoice.description
      ..status = invoice.status.name
      ..createdAt = invoice.createdAt
      ..expiresAt = invoice.expiresAt
      ..paidAt = invoice.paidAt
      ..paymentTxid = invoice.paymentTxid
      ..amountReceived = invoice.amountReceived?.toString()
      ..metadataJson = _encodeJson(invoice.metadata)
      ..outputsJson = outputs == null
          ? null
          : jsonEncode(outputs.map((o) => o.toMap()).toList());
  }

  /// Convert to the invoice read model (audit S-07: previously a Map).
  InvoiceReadModel toDomain() {
    final rawOutputs = outputsJson;
    return InvoiceReadModel(
      invoiceId: invoiceId,
      walletId: walletId,
      addresses: _decodeList(addressesJson),
      amount: BigInt.parse(amount),
      outputs: rawOutputs == null
          ? null
          : (jsonDecode(rawOutputs) as List)
              .map((o) => InvoiceOutputSpec.fromMap(
                  Map<String, dynamic>.from(o as Map)))
              .toList(),
      description: description,
      status: InvoiceStatus.values.firstWhere(
        (s) => s.name == status,
        orElse: () => InvoiceStatus.pending,
      ),
      createdAt: createdAt,
      expiresAt: expiresAt,
      paidAt: paidAt,
      paymentTxid: paymentTxid,
      amountReceived:
          amountReceived != null ? BigInt.parse(amountReceived!) : null,
      lastUpdated: paidAt ?? createdAt,
      metadata: metadataJson != null
          ? _decodeJson(metadataJson!)
          : <String, dynamic>{},
    );
  }

  /// Serialize to JSON for backup
  Map<String, dynamic> toJson() {
    return {
      'invoiceId': invoiceId,
      'walletId': walletId,
      'addressesJson': addressesJson,
      'amount': amount,
      'description': description,
      'status': status,
      'createdAt': createdAt.toIso8601String(),
      'expiresAt': expiresAt?.toIso8601String(),
      'paidAt': paidAt?.toIso8601String(),
      'paymentTxid': paymentTxid,
      'amountReceived': amountReceived,
      'metadataJson': metadataJson,
      'outputsJson': outputsJson,
    };
  }

  /// Deserialize from JSON for restore
  factory InvoiceEntity.fromJson(Map<String, dynamic> json) {
    return InvoiceEntity()
      ..invoiceId = json['invoiceId'] as String
      ..walletId = json['walletId'] as String
      ..addressesJson = json['addressesJson'] as String
      ..amount = json['amount'] as String
      ..description = json['description'] as String?
      ..status = json['status'] as String
      ..createdAt = DateTime.parse(json['createdAt'] as String)
      ..expiresAt = json['expiresAt'] != null ? DateTime.parse(json['expiresAt'] as String) : null
      ..paidAt = json['paidAt'] != null ? DateTime.parse(json['paidAt'] as String) : null
      ..paymentTxid = json['paymentTxid'] as String?
      ..amountReceived = json['amountReceived'] as String?
      ..metadataJson = json['metadataJson'] as String?
      ..outputsJson = json['outputsJson'] as String?;
  }
}

// Helper functions for JSON serialization in entities
String _encodeList(List<String> list) {
  return list.join(',');
}

List<String> _decodeList(String json) {
  if (json.isEmpty) return [];
  return json.split(',');
}

String _encodeJson(Map<String, dynamic> map) {
  return jsonEncode(map);
}

Map<String, dynamic> _decodeJson(String json) {
  if (json.isEmpty || json == '{}') return {};
  return Map<String, dynamic>.from(jsonDecode(json) as Map);
} 

/// The where clauses of the single-property indexes that audit S-16 turned
/// into composite indexes, kept for hosts that query these collections
/// directly. They use the new indexes' prefixes and return the same rows.
extension AddressEntityFormerWhereClauses on QueryBuilder<AddressEntity, AddressEntity, QWhereClause> {
  @Deprecated('Use walletIdEqualToAnyPurpose (the walletId index is now (walletId, purpose)).')
  QueryBuilder<AddressEntity, AddressEntity, QAfterWhereClause> walletIdEqualTo(String walletId) =>
      walletIdEqualToAnyPurpose(walletId);

  @Deprecated('Use walletIdNotEqualToAnyPurpose (the walletId index is now (walletId, purpose)).')
  QueryBuilder<AddressEntity, AddressEntity, QAfterWhereClause> walletIdNotEqualTo(String walletId) =>
      walletIdNotEqualToAnyPurpose(walletId);
}

/// See [AddressEntityFormerWhereClauses].
extension BitcoinTransactionEntityFormerWhereClauses
    on QueryBuilder<BitcoinTransactionEntity, BitcoinTransactionEntity, QWhereClause> {
  @Deprecated('Use statusEqualToAnyWalletId (the status index is now (status, walletId)).')
  QueryBuilder<BitcoinTransactionEntity, BitcoinTransactionEntity, QAfterWhereClause> statusEqualTo(
          String status) =>
      statusEqualToAnyWalletId(status);

  @Deprecated('Use statusNotEqualToAnyWalletId (the status index is now (status, walletId)).')
  QueryBuilder<BitcoinTransactionEntity, BitcoinTransactionEntity, QAfterWhereClause> statusNotEqualTo(
          String status) =>
      statusNotEqualToAnyWalletId(status);
}
