import 'package:isar/isar.dart';
import 'package:spiffynode/spiffy_node.dart';
import 'read_model_storage.dart';
import '../models/bitcoin_utxo.dart';
import '../models/bitcoin_transaction.dart';

part 'libspiffy_schemas.g.dart';

/// LibSpiffy's Isar schemas that developers can add to their Isar instance.
/// 
/// Usage:
/// ```dart
/// // After running: dart run build_runner build
/// final isar = await Isar.open([
///   ...LibSpiffySchemas.walletSchemas,  // LibSpiffy's schemas
///   UserSchema,                         // Developer's own schemas
///   OrderSchema,
///   ProductSchema,
/// ]);
/// 
/// final walletStorage = IsarWalletStorage(isar);
/// ```
class LibSpiffySchemas {
  /// All wallet-related schemas for LibSpiffy
  /// Note: These schemas are generated by Isar after running build_runner
  ///
  /// WalletEventEntity is NOT included here as it's managed by Eventador separately.
  static List<CollectionSchema<dynamic>> get walletSchemas {
    // Generated schemas from build_runner
    return [
      BlockHeaderEntitySchema,
      MerkleProofEntitySchema,
      BitcoinUtxoEntitySchema,
      BitcoinTransactionEntitySchema,
      WalletMetadataEntitySchema,
    ];
  }
}

/// Block header storage entity for SPV validation
@collection
class BlockHeaderEntity {
  Id id = Isar.autoIncrement;

  /// Block height
  @Index()
  late int height;

  /// Block hash (hex string)
  @Index(unique: true)
  late String hash;

  /// Previous block hash
  late String prevBlockHash;

  /// Merkle root hash
  late String merkleRoot;

  /// Block timestamp (Unix timestamp)
  late int timestamp;

  /// Block version
  late int version;

  /// Difficulty bits
  late int bits;

  /// Block nonce
  late int nonce;

  /// Whether this header is orphaned due to reorganization
  @Index()
  late bool isOrphaned;

  /// When this header was stored
  late DateTime storedAt;

  BlockHeaderEntity();

  /// Create from SpiffyNode BlockHeader
  factory BlockHeaderEntity.fromBlockHeader(BlockHeader blockHeader, int height) {
    return BlockHeaderEntity()
      ..height = height
      ..hash = blockHeader.blockHash().toString()
      ..prevBlockHash = blockHeader.prevBlock.toString()
      ..merkleRoot = blockHeader.merkleRoot.toString()
      ..timestamp = blockHeader.timestamp.millisecondsSinceEpoch ~/ 1000
      ..version = blockHeader.version
      ..bits = blockHeader.bits
      ..nonce = blockHeader.nonce
      ..isOrphaned = false
      ..storedAt = DateTime.now();
  }

  /// Convert back to SpiffyNode BlockHeader
  /// Note: This reconstructs the BlockHeader from stored values
  BlockHeader toBlockHeader() {
    return BlockHeader(
      version: version,
      prevBlock: Hash.fromHex(prevBlockHash),
      merkleRoot: Hash.fromHex(merkleRoot),
      timestamp: DateTime.fromMillisecondsSinceEpoch(timestamp * 1000),
      bits: bits,
      nonce: nonce,
    );
  }
}

/// Merkle proof storage entity for SPV validation
@collection
class MerkleProofEntity {
  Id id = Isar.autoIncrement;

  /// Transaction ID this proof is for
  @Index()
  late String txid;

  /// Block hash containing this transaction
  @Index()
  late String blockHash;

  /// Block height
  late int blockHeight;

  /// Position of transaction in block
  late int position;

  /// Merkle proof hashes (serialized as JSON)
  late String merkleProofJson;

  /// When this proof was stored
  late DateTime createdAt;

  MerkleProofEntity();

  /// Create from MerkleProof
  factory MerkleProofEntity.fromMerkleProof(MerkleProof proof) {
    return MerkleProofEntity()
      ..txid = proof.txid
      ..blockHash = proof.blockHash
      ..blockHeight = proof.blockHeight
      ..position = proof.position
      ..merkleProofJson = proof.merkleProof.join(',')
      ..createdAt = proof.createdAt;
  }

  /// Convert back to MerkleProof
  MerkleProof toMerkleProof() {
    return MerkleProof(
      blockHash: blockHash,
      txid: txid,
      merkleProof: merkleProofJson.split(','),
      position: position,
      blockHeight: blockHeight,
      createdAt: createdAt,
    );
  }
}

/// Wallet event storage entity for event sourcing
@collection
class WalletEventEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this event belongs to
  @Index()
  late String walletId;

  /// Event version/sequence number
  @Index()
  late int version;

  /// Event type (e.g., 'UTXOReceived', 'TransactionCreated')
  late String eventType;

  /// Event data (serialized as JSON)
  late String eventData;

  /// When this event occurred
  @Index()
  late DateTime timestamp;

  /// Aggregate version after this event
  late int aggregateVersion;

  WalletEventEntity();
}

/// Bitcoin UTXO storage entity
@collection
class BitcoinUtxoEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this UTXO belongs to
  @Index()
  late String walletId;

  /// Transaction ID
  @Index()
  late String txid;

  /// Output index
  late int vout;

  /// UTXO key (txid:vout)
  @Index(unique: true)
  late String utxoKey;

  /// Value in satoshis (as string to handle BigInt)
  late String satoshis;

  /// Script public key (hex)
  late String scriptPubKey;

  /// Address (if derivable)
  String? address;

  /// Block height where this UTXO was created
  int? blockHeight;

  /// Number of confirmations
  late int confirmations;

  /// UTXO status ('available', 'reserved', 'spent')
  @Index()
  late String status;

  /// When this UTXO was created
  late DateTime createdAt;

  /// When this UTXO was spent (if applicable)
  DateTime? spentAt;

  /// Transaction ID that spent this UTXO (if applicable)
  String? spentInTxId;

  /// Script type ('p2pkh', 'p2sh', 'multisig', etc.)
  late String scriptType;

  /// Whether this UTXO is spendable by the wallet
  late bool isSpendable;

  /// UTXO category ('funding', 'special', 'protocol')
  late String category;

  BitcoinUtxoEntity();

  /// Create from domain model BitcoinUtxo
  factory BitcoinUtxoEntity.fromDomain(BitcoinUtxo utxo) {
    return BitcoinUtxoEntity()
      ..walletId = '' // Will be set by the storage implementation
      ..txid = utxo.txid
      ..vout = utxo.vout
      ..utxoKey = '${utxo.txid}:${utxo.vout}'
      ..satoshis = utxo.satoshis.toString()
      ..scriptPubKey = utxo.scriptPubKey
      ..address = utxo.address
      ..blockHeight = utxo.blockHeight
      ..confirmations = utxo.confirmations ?? 0
      ..status = utxo.status.name
      ..createdAt = utxo.createdAt
      ..spentAt = utxo.status == UTXOStatus.spent ? utxo.updatedAt : null
      ..spentInTxId = null // This info would come from spending transaction
      ..scriptType = 'p2pkh' // Default, could be enhanced
      ..isSpendable = utxo.status == UTXOStatus.available
      ..category = 'funding'; // Default category
  }

  /// Convert back to domain model BitcoinUtxo
  BitcoinUtxo toDomain() {
    return BitcoinUtxo.create(
      txid: txid,
      vout: vout,
      satoshis: BigInt.parse(satoshis),
      scriptPubKey: scriptPubKey,
      address: address ?? '',
      blockHeight: blockHeight,
      confirmations: confirmations,
    );
  }
}

/// Bitcoin transaction storage entity
@collection
class BitcoinTransactionEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID this transaction belongs to
  @Index()
  late String walletId;

  /// Transaction ID
  @Index(unique: true)
  late String txid;

  /// Raw transaction hex
  late String rawHex;

  /// Block height (null if unconfirmed)
  int? blockHeight;

  /// Block hash (null if unconfirmed)
  String? blockHash;

  /// Number of confirmations
  late int confirmations;

  /// Total input amount (as string to handle BigInt)
  late String totalInput;

  /// Total output amount (as string to handle BigInt)
  late String totalOutput;

  /// Transaction fee (as string to handle BigInt)
  late String fee;

  /// Whether this is an incoming transaction
  late bool isIncoming;

  /// Whether this is an outgoing transaction
  late bool isOutgoing;

  /// Transaction status ('pending', 'confirmed', 'failed')
  @Index()
  late String status;

  /// When this transaction was created/received
  @Index()
  late DateTime createdAt;

  /// When this transaction was confirmed (if applicable)
  DateTime? confirmedAt;

  /// When this transaction was broadcast
  DateTime? broadcastAt;

  /// Counterparty information (who sent/received)
  String? counterparty;

  /// Notes or metadata about this transaction
  String? notes;

  BitcoinTransactionEntity();

  /// Create from domain model BitcoinTransaction
  factory BitcoinTransactionEntity.fromDomain(BitcoinTransaction tx) {
    // Calculate net amount (positive for incoming, negative for outgoing)
    final netAmount = tx.netAmount;
    
    return BitcoinTransactionEntity()
      ..walletId = '' // Will be set by the storage implementation
      ..txid = tx.txid
      ..rawHex = tx.rawHex
      ..blockHeight = tx.blockHeight
      ..blockHash = tx.blockHeight != null ? '' : null // Would need actual hash
      ..confirmations = tx.confirmations ?? 0
      ..totalInput = tx.inputValue.toString()
      ..totalOutput = tx.outputValue.toString()
      ..fee = tx.fee.toString()
      ..isIncoming = netAmount > BigInt.zero
      ..isOutgoing = netAmount < BigInt.zero
      ..status = tx.status.name
      ..createdAt = tx.createdAt
      ..confirmedAt = null // Not directly available in model
      ..broadcastAt = null // Not directly available in model
      ..counterparty = null
      ..notes = tx.memo;
  }

  /// Convert back to domain model BitcoinTransaction
  BitcoinTransaction toDomain() {
    return BitcoinTransaction(
      txid: txid,
      rawHex: rawHex,
      status: TransactionStatus.values.firstWhere((s) => s.name == status),
      blockHeight: blockHeight,
      confirmations: confirmations,
      inputValue: BigInt.parse(totalInput),
      outputValue: BigInt.parse(totalOutput),
      fee: BigInt.parse(fee),
      receivingAddresses: [], // Would need to store these separately
      sendingAddresses: [], // Would need to store these separately
      netAmount: BigInt.parse(totalInput) - BigInt.parse(totalOutput),
      createdAt: createdAt,
      updatedAt: createdAt, // Use createdAt as fallback
      memo: notes,
      lockTime: 0, // Would need to parse from rawHex or store separately
      version: 1, // Would need to parse from rawHex or store separately
    );
  }
}

/// Wallet metadata storage entity
@collection
class WalletMetadataEntity {
  Id id = Isar.autoIncrement;

  /// Wallet ID
  @Index(unique: true)
  late String walletId;

  /// Wallet name
  late String name;

  /// Wallet type ('hd', 'single', 'multisig')
  late String walletType;

  /// Network ('mainnet', 'testnet', 'regtest')
  late String network;

  /// Root address (if applicable)
  String? rootAddress;

  /// Current derivation index for HD wallets
  late int derivationIndex;

  /// Whether the wallet is created/initialized
  late bool isCreated;

  /// When this wallet was created
  late DateTime createdAt;

  /// Last time this wallet was accessed
  late DateTime lastAccessedAt;

  /// Wallet metadata (serialized as JSON)
  late String metadataJson;

  /// Current aggregate version
  late int aggregateVersion;

  /// Cached confirmed balance (as string to handle BigInt)
  late String confirmedBalance;

  /// Cached unconfirmed balance (as string to handle BigInt)
  late String unconfirmedBalance;

  /// List of wallet addresses (serialized as JSON)
  late String addressesJson;

  /// List of wallet public keys (serialized as JSON)
  late String publicKeysJson;

  WalletMetadataEntity();
} 