// Mocks generated by Mockito 5.4.4 from annotations
// in libspiffy/test/services/block_header_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:logging/logging.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spiffynode/src/chaincfg/hash.dart' as _i5;
import 'package:spiffynode/src/spv/chain_tip_tracker.dart' as _i2;
import 'package:spiffynode/src/wire/messages.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChainTipTrackerConfig_0 extends _i1.SmartFake
    implements _i2.ChainTipTrackerConfig {
  _FakeChainTipTrackerConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_1 extends _i1.SmartFake implements _i3.Logger {
  _FakeLogger_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChainTipTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockChainTipTracker extends _i1.Mock implements _i2.ChainTipTracker {
  MockChainTipTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChainTipTrackerConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeChainTipTrackerConfig_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.ChainTipTrackerConfig);

  @override
  _i3.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_1(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i3.Logger);

  @override
  int get networkHeight => (super.noSuchMethod(
        Invocation.getter(#networkHeight),
        returnValue: 0,
      ) as int);

  @override
  int get activePeerCount => (super.noSuchMethod(
        Invocation.getter(#activePeerCount),
        returnValue: 0,
      ) as int);

  @override
  _i4.Stream<_i2.ChainTipEvent> get tipEvents => (super.noSuchMethod(
        Invocation.getter(#tipEvents),
        returnValue: _i4.Stream<_i2.ChainTipEvent>.empty(),
      ) as _i4.Stream<_i2.ChainTipEvent>);

  @override
  Map<String, dynamic> get statistics => (super.noSuchMethod(
        Invocation.getter(#statistics),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isLikelySynced => (super.noSuchMethod(
        Invocation.getter(#isLikelySynced),
        returnValue: false,
      ) as bool);

  @override
  bool get isPotentialReorg => (super.noSuchMethod(
        Invocation.getter(#isPotentialReorg),
        returnValue: false,
      ) as bool);

  @override
  List<Map<String, dynamic>> get potentialReorgs => (super.noSuchMethod(
        Invocation.getter(#potentialReorgs),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  void registerPeer(String? peerId) => super.noSuchMethod(
        Invocation.method(
          #registerPeer,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterPeer(String? peerId) => super.noSuchMethod(
        Invocation.method(
          #unregisterPeer,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePeerTip(
    String? peerId,
    _i5.Hash? blockHash,
    int? height,
    _i2.ChainTipSource? source,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePeerTip,
          [
            peerId,
            blockHash,
            height,
            source,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleVersion(
    String? peerId,
    _i6.MsgVersion? version,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleVersion,
          [
            peerId,
            version,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleBlockAnnouncement(
    String? peerId,
    _i5.Hash? blockHash,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleBlockAnnouncement,
          [
            peerId,
            blockHash,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleHeaders(
    String? peerId,
    _i6.MsgHeaders? headers,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleHeaders,
          [
            peerId,
            headers,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getBestPeers() => (super.noSuchMethod(
        Invocation.method(
          #getBestPeers,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i4.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
