// Mocks generated by Mockito 5.4.4 from annotations
// in libspiffy/test/services/spv_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:libspiffy/src/services/arc_service.dart' as _i2;
import 'package:libspiffy/src/services/block_header_service.dart' as _i5;
import 'package:logging/logging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:spiffynode/src/chaincfg/hash.dart' as _i8;
import 'package:spiffynode/src/spv/chain_tip_tracker.dart' as _i3;
import 'package:spiffynode/src/wire/block_header.dart' as _i10;
import 'package:spiffynode/src/wire/messages.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArcSubmitResponse_0 extends _i1.SmartFake
    implements _i2.ArcSubmitResponse {
  _FakeArcSubmitResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArcTransactionResponse_1 extends _i1.SmartFake
    implements _i2.ArcTransactionResponse {
  _FakeArcTransactionResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArcPolicyResponse_2 extends _i1.SmartFake
    implements _i2.ArcPolicyResponse {
  _FakeArcPolicyResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArcHealthResponse_3 extends _i1.SmartFake
    implements _i2.ArcHealthResponse {
  _FakeArcHealthResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChainTipTrackerConfig_4 extends _i1.SmartFake
    implements _i3.ChainTipTrackerConfig {
  _FakeChainTipTrackerConfig_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_5 extends _i1.SmartFake implements _i4.Logger {
  _FakeLogger_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChainTipTracker_6 extends _i1.SmartFake
    implements _i3.ChainTipTracker {
  _FakeChainTipTracker_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBlockHeaderServiceConfig_7 extends _i1.SmartFake
    implements _i5.BlockHeaderServiceConfig {
  _FakeBlockHeaderServiceConfig_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArcService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArcService extends _i1.Mock implements _i2.ArcService {
  MockArcService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i7.Future<_i2.ArcSubmitResponse> submitTransaction(
    String? rawTx, {
    String? callbackUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitTransaction,
          [rawTx],
          {#callbackUrl: callbackUrl},
        ),
        returnValue:
            _i7.Future<_i2.ArcSubmitResponse>.value(_FakeArcSubmitResponse_0(
          this,
          Invocation.method(
            #submitTransaction,
            [rawTx],
            {#callbackUrl: callbackUrl},
          ),
        )),
      ) as _i7.Future<_i2.ArcSubmitResponse>);

  @override
  _i7.Future<_i2.ArcSubmitResponse> submitBEEF(
    String? beefHex, {
    String? callbackUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitBEEF,
          [beefHex],
          {#callbackUrl: callbackUrl},
        ),
        returnValue:
            _i7.Future<_i2.ArcSubmitResponse>.value(_FakeArcSubmitResponse_0(
          this,
          Invocation.method(
            #submitBEEF,
            [beefHex],
            {#callbackUrl: callbackUrl},
          ),
        )),
      ) as _i7.Future<_i2.ArcSubmitResponse>);

  @override
  _i7.Future<_i2.ArcTransactionResponse> getTransaction(String? txid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [txid],
        ),
        returnValue: _i7.Future<_i2.ArcTransactionResponse>.value(
            _FakeArcTransactionResponse_1(
          this,
          Invocation.method(
            #getTransaction,
            [txid],
          ),
        )),
      ) as _i7.Future<_i2.ArcTransactionResponse>);

  @override
  _i7.Future<String> getRawTransaction(String? txid) => (super.noSuchMethod(
        Invocation.method(
          #getRawTransaction,
          [txid],
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getRawTransaction,
            [txid],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i2.ArcMerkleProofResponse?> getMerkleProof(String? txid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMerkleProof,
          [txid],
        ),
        returnValue: _i7.Future<_i2.ArcMerkleProofResponse?>.value(),
      ) as _i7.Future<_i2.ArcMerkleProofResponse?>);

  @override
  _i7.Future<List<_i2.ArcMerkleProofResponse>> getBatchMerkleProofs(
          List<String>? txids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchMerkleProofs,
          [txids],
        ),
        returnValue: _i7.Future<List<_i2.ArcMerkleProofResponse>>.value(
            <_i2.ArcMerkleProofResponse>[]),
      ) as _i7.Future<List<_i2.ArcMerkleProofResponse>>);

  @override
  _i7.Future<_i2.ArcPolicyResponse> getPolicy() => (super.noSuchMethod(
        Invocation.method(
          #getPolicy,
          [],
        ),
        returnValue:
            _i7.Future<_i2.ArcPolicyResponse>.value(_FakeArcPolicyResponse_2(
          this,
          Invocation.method(
            #getPolicy,
            [],
          ),
        )),
      ) as _i7.Future<_i2.ArcPolicyResponse>);

  @override
  _i7.Future<_i2.ArcHealthResponse> getHealth() => (super.noSuchMethod(
        Invocation.method(
          #getHealth,
          [],
        ),
        returnValue:
            _i7.Future<_i2.ArcHealthResponse>.value(_FakeArcHealthResponse_3(
          this,
          Invocation.method(
            #getHealth,
            [],
          ),
        )),
      ) as _i7.Future<_i2.ArcHealthResponse>);

  @override
  _i7.Future<List<_i2.ArcSubmitResponse>> submitBatchTransactions(
    List<String>? rawTxs, {
    String? callbackUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitBatchTransactions,
          [rawTxs],
          {#callbackUrl: callbackUrl},
        ),
        returnValue: _i7.Future<List<_i2.ArcSubmitResponse>>.value(
            <_i2.ArcSubmitResponse>[]),
      ) as _i7.Future<List<_i2.ArcSubmitResponse>>);

  @override
  _i7.Future<List<_i2.ArcTransactionResponse>> getBatchTransactions(
          List<String>? txids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchTransactions,
          [txids],
        ),
        returnValue: _i7.Future<List<_i2.ArcTransactionResponse>>.value(
            <_i2.ArcTransactionResponse>[]),
      ) as _i7.Future<List<_i2.ArcTransactionResponse>>);

  @override
  _i7.Future<BigInt> estimateFee({
    required int? inputCount,
    required int? outputCount,
    int? dataSize = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateFee,
          [],
          {
            #inputCount: inputCount,
            #outputCount: outputCount,
            #dataSize: dataSize,
          },
        ),
        returnValue: _i7.Future<BigInt>.value(_i6.dummyValue<BigInt>(
          this,
          Invocation.method(
            #estimateFee,
            [],
            {
              #inputCount: inputCount,
              #outputCount: outputCount,
              #dataSize: dataSize,
            },
          ),
        )),
      ) as _i7.Future<BigInt>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChainTipTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockChainTipTracker extends _i1.Mock implements _i3.ChainTipTracker {
  MockChainTipTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChainTipTrackerConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeChainTipTrackerConfig_4(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.ChainTipTrackerConfig);

  @override
  _i4.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_5(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i4.Logger);

  @override
  int get networkHeight => (super.noSuchMethod(
        Invocation.getter(#networkHeight),
        returnValue: 0,
      ) as int);

  @override
  int get activePeerCount => (super.noSuchMethod(
        Invocation.getter(#activePeerCount),
        returnValue: 0,
      ) as int);

  @override
  _i7.Stream<_i3.ChainTipEvent> get tipEvents => (super.noSuchMethod(
        Invocation.getter(#tipEvents),
        returnValue: _i7.Stream<_i3.ChainTipEvent>.empty(),
      ) as _i7.Stream<_i3.ChainTipEvent>);

  @override
  Map<String, dynamic> get statistics => (super.noSuchMethod(
        Invocation.getter(#statistics),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get isLikelySynced => (super.noSuchMethod(
        Invocation.getter(#isLikelySynced),
        returnValue: false,
      ) as bool);

  @override
  bool get isPotentialReorg => (super.noSuchMethod(
        Invocation.getter(#isPotentialReorg),
        returnValue: false,
      ) as bool);

  @override
  List<Map<String, dynamic>> get potentialReorgs => (super.noSuchMethod(
        Invocation.getter(#potentialReorgs),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  void registerPeer(String? peerId) => super.noSuchMethod(
        Invocation.method(
          #registerPeer,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterPeer(String? peerId) => super.noSuchMethod(
        Invocation.method(
          #unregisterPeer,
          [peerId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePeerTip(
    String? peerId,
    _i8.Hash? blockHash,
    int? height,
    _i3.ChainTipSource? source,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePeerTip,
          [
            peerId,
            blockHash,
            height,
            source,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleVersion(
    String? peerId,
    _i9.MsgVersion? version,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleVersion,
          [
            peerId,
            version,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleBlockAnnouncement(
    String? peerId,
    _i8.Hash? blockHash,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleBlockAnnouncement,
          [
            peerId,
            blockHash,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleHeaders(
    String? peerId,
    _i9.MsgHeaders? headers,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #handleHeaders,
          [
            peerId,
            headers,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getBestPeers() => (super.noSuchMethod(
        Invocation.method(
          #getBestPeers,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i7.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [BlockHeaderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockHeaderService extends _i1.Mock
    implements _i5.BlockHeaderService {
  MockBlockHeaderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChainTipTracker get chainTipTracker => (super.noSuchMethod(
        Invocation.getter(#chainTipTracker),
        returnValue: _FakeChainTipTracker_6(
          this,
          Invocation.getter(#chainTipTracker),
        ),
      ) as _i3.ChainTipTracker);

  @override
  _i5.BlockHeaderServiceConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeBlockHeaderServiceConfig_7(
          this,
          Invocation.getter(#config),
        ),
      ) as _i5.BlockHeaderServiceConfig);

  @override
  int get headerCount => (super.noSuchMethod(
        Invocation.getter(#headerCount),
        returnValue: 0,
      ) as int);

  @override
  int get chainHeight => (super.noSuchMethod(
        Invocation.getter(#chainHeight),
        returnValue: 0,
      ) as int);

  @override
  _i7.Stream<_i5.BlockHeaderEvent> get headerEvents => (super.noSuchMethod(
        Invocation.getter(#headerEvents),
        returnValue: _i7.Stream<_i5.BlockHeaderEvent>.empty(),
      ) as _i7.Stream<_i5.BlockHeaderEvent>);

  @override
  Map<String, dynamic> get statistics => (super.noSuchMethod(
        Invocation.getter(#statistics),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<void> processHeaders(
    _i9.MsgHeaders? headersMessage,
    String? peerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processHeaders,
          [
            headersMessage,
            peerId,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  String? getMerkleRoot(int? blockHeight) =>
      (super.noSuchMethod(Invocation.method(
        #getMerkleRoot,
        [blockHeight],
      )) as String?);

  @override
  _i10.BlockHeader? getHeader(int? blockHeight) =>
      (super.noSuchMethod(Invocation.method(
        #getHeader,
        [blockHeight],
      )) as _i10.BlockHeader?);

  @override
  _i10.BlockHeader? getHeaderByHash(_i8.Hash? blockHash) =>
      (super.noSuchMethod(Invocation.method(
        #getHeaderByHash,
        [blockHash],
      )) as _i10.BlockHeader?);

  @override
  List<_i10.BlockHeader> getHeadersInRange(
    int? startHeight,
    int? endHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHeadersInRange,
          [
            startHeight,
            endHeight,
          ],
        ),
        returnValue: <_i10.BlockHeader>[],
      ) as List<_i10.BlockHeader>);

  @override
  bool validateHeaderChain(List<_i10.BlockHeader>? headers) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateHeaderChain,
          [headers],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasContinuousChain(int? toHeight) => (super.noSuchMethod(
        Invocation.method(
          #hasContinuousChain,
          [toHeight],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<int> getMissingHeights(
    int? startHeight,
    int? endHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMissingHeights,
          [
            startHeight,
            endHeight,
          ],
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  void cleanupOrphanedHeaders() => super.noSuchMethod(
        Invocation.method(
          #cleanupOrphanedHeaders,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> shutdown() => (super.noSuchMethod(
        Invocation.method(
          #shutdown,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
