/// Encryption service for secure storage.
///
/// Provides AES-256-GCM encryption with HKDF key derivation for
/// encrypting sensitive data like xpubs in server-side deployments.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

/// Result of an encryption operation.
///
/// Contains the ciphertext and nonce needed for decryption.
class EncryptionResult {
  /// The encrypted data (ciphertext + authentication tag).
  final Uint8List ciphertext;

  /// The nonce used for encryption (must be unique per encryption).
  final Uint8List nonce;

  const EncryptionResult({
    required this.ciphertext,
    required this.nonce,
  });
}

/// Service for encrypting and decrypting sensitive data.
///
/// Uses AES-256-GCM for authenticated encryption with HKDF for
/// deriving per-secret encryption keys from a master key.
///
/// Example:
/// ```dart
/// final service = EncryptionService(masterKey: masterKeyBytes);
/// final result = await service.encrypt(
///   plaintext: 'xpub6...',
///   context: 'wallet_xpub_abc123',
/// );
/// final decrypted = await service.decrypt(
///   ciphertext: result.ciphertext,
///   nonce: result.nonce,
///   context: 'wallet_xpub_abc123',
/// );
/// ```
class EncryptionService {
  /// The master key used for HKDF derivation.
  final Uint8List _masterKey;

  /// The key version for rotation support.
  final int keyVersion;

  /// Salt used for HKDF (should be application-specific).
  static const String _hkdfSalt = 'libspiffy-xpub-v1';

  /// AES-GCM cipher with 256-bit keys.
  final AesGcm _cipher = AesGcm.with256bits();

  /// HKDF algorithm with SHA-256, outputting 32-byte keys.
  final Hkdf _hkdf = Hkdf(hmac: Hmac.sha256(), outputLength: 32);

  /// Creates an encryption service with the given master key.
  ///
  /// The [masterKey] must be exactly 32 bytes (256 bits).
  /// The [keyVersion] is used for key rotation tracking (default: 1).
  ///
  /// Throws [ArgumentError] if the master key is not 32 bytes.
  EncryptionService({
    required Uint8List masterKey,
    this.keyVersion = 1,
  }) : _masterKey = masterKey {
    if (masterKey.length != 32) {
      throw ArgumentError(
        'Master key must be exactly 32 bytes (256 bits), '
        'got ${masterKey.length} bytes',
      );
    }
  }

  /// Creates an encryption service from a base64-encoded master key.
  ///
  /// This is useful when loading the master key from an environment variable.
  ///
  /// Throws [FormatException] if the base64 is invalid.
  /// Throws [ArgumentError] if the decoded key is not 32 bytes.
  factory EncryptionService.fromBase64({
    required String masterKeyBase64,
    int keyVersion = 1,
  }) {
    final decoded = base64.decode(masterKeyBase64);
    return EncryptionService(
      masterKey: Uint8List.fromList(decoded),
      keyVersion: keyVersion,
    );
  }

  /// Derives a per-secret encryption key using HKDF.
  ///
  /// The [context] should be unique per secret (e.g., "wallet_xpub_abc123").
  /// This ensures that even with the same master key, each secret has a
  /// unique encryption key.
  Future<SecretKey> _deriveKey(String context) async {
    final masterSecretKey = SecretKey(_masterKey);
    final saltBytes = utf8.encode(_hkdfSalt);
    final infoBytes = utf8.encode(context);

    final derivedKey = await _hkdf.deriveKey(
      secretKey: masterSecretKey,
      nonce: saltBytes,
      info: infoBytes,
    );

    return derivedKey;
  }

  /// Encrypts plaintext data.
  ///
  /// Parameters:
  /// - [plaintext]: The string to encrypt.
  /// - [context]: Unique context for key derivation (e.g., "wallet_xpub_abc123").
  ///
  /// Returns an [EncryptionResult] containing the ciphertext and nonce.
  ///
  /// Throws [EncryptionException] if encryption fails.
  Future<EncryptionResult> encrypt({
    required String plaintext,
    required String context,
  }) async {
    try {
      final derivedKey = await _deriveKey(context);
      final plaintextBytes = utf8.encode(plaintext);

      // Encrypt with a random nonce (generated by the cipher)
      final secretBox = await _cipher.encrypt(
        plaintextBytes,
        secretKey: derivedKey,
      );

      // Combine ciphertext and MAC (authentication tag)
      final ciphertextWithMac = Uint8List.fromList([
        ...secretBox.cipherText,
        ...secretBox.mac.bytes,
      ]);

      return EncryptionResult(
        ciphertext: ciphertextWithMac,
        nonce: Uint8List.fromList(secretBox.nonce),
      );
    } catch (e) {
      throw EncryptionException('Failed to encrypt data: $e');
    }
  }

  /// Decrypts ciphertext data.
  ///
  /// Parameters:
  /// - [ciphertext]: The encrypted data (ciphertext + MAC).
  /// - [nonce]: The nonce used during encryption.
  /// - [context]: The same context used during encryption.
  ///
  /// Returns the decrypted plaintext string.
  ///
  /// Throws [EncryptionException] if decryption fails or authentication fails.
  Future<String> decrypt({
    required Uint8List ciphertext,
    required Uint8List nonce,
    required String context,
  }) async {
    try {
      final derivedKey = await _deriveKey(context);

      // Split ciphertext and MAC (last 16 bytes is the MAC for AES-GCM)
      const macLength = 16;
      if (ciphertext.length < macLength) {
        throw EncryptionException('Ciphertext too short');
      }

      final actualCiphertext = ciphertext.sublist(0, ciphertext.length - macLength);
      final macBytes = ciphertext.sublist(ciphertext.length - macLength);

      final secretBox = SecretBox(
        actualCiphertext,
        nonce: nonce,
        mac: Mac(macBytes),
      );

      final plaintextBytes = await _cipher.decrypt(
        secretBox,
        secretKey: derivedKey,
      );

      return utf8.decode(plaintextBytes);
    } on SecretBoxAuthenticationError {
      throw EncryptionException(
        'Decryption failed: authentication error (wrong key or tampered data)',
      );
    } catch (e) {
      if (e is EncryptionException) rethrow;
      throw EncryptionException('Failed to decrypt data: $e');
    }
  }

  /// Generates a new random master key.
  ///
  /// Use this to generate a master key for new deployments.
  /// The key should be stored securely (e.g., in an environment variable
  /// or secrets manager).
  ///
  /// Returns 32 random bytes suitable for use as a master key.
  static Future<Uint8List> generateMasterKey() async {
    final algorithm = AesGcm.with256bits();
    final secretKey = await algorithm.newSecretKey();
    final keyBytes = await secretKey.extractBytes();
    return Uint8List.fromList(keyBytes);
  }

  /// Generates a new random master key and returns it as base64.
  ///
  /// This is convenient for storing in environment variables.
  static Future<String> generateMasterKeyBase64() async {
    final keyBytes = await generateMasterKey();
    return base64.encode(keyBytes);
  }
}

/// Exception thrown when encryption or decryption fails.
class EncryptionException implements Exception {
  final String message;

  const EncryptionException(this.message);

  @override
  String toString() => 'EncryptionException: $message';
}