// Mocks generated by Mockito 5.4.4 from annotations
// in libspiffy/test/unit/postgres_secure_storage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:math' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:postgres/postgres.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T> extends _i1.SmartFake implements _i2.Future<T> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStatement_1 extends _i1.SmartFake implements _i3.Statement {
  _FakeStatement_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_2 extends _i1.SmartFake implements _i3.Result {
  _FakeResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIterator_3<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResultRow_4 extends _i1.SmartFake implements _i3.ResultRow {
  _FakeResultRow_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Pool].
///
/// See the documentation for Mockito's code generation for more information.
class MockPool<L> extends _i1.Mock implements _i3.Pool<L> {
  MockPool() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  _i2.Future<void> get closed => (super.noSuchMethod(
        Invocation.getter(#closed),
        returnValue: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<R> withConnection<R>(
    _i2.Future<R> Function(_i3.Connection)? fn, {
    _i3.ConnectionSettings? settings,
    L? locality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #withConnection,
          [fn],
          {
            #settings: settings,
            #locality: locality,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #withConnection,
                  [fn],
                  {
                    #settings: settings,
                    #locality: locality,
                  },
                ),
              ),
              (R v) => _i2.Future<R>.value(v),
            ) ??
            _FakeFuture_0<R>(
              this,
              Invocation.method(
                #withConnection,
                [fn],
                {
                  #settings: settings,
                  #locality: locality,
                },
              ),
            ),
      ) as _i2.Future<R>);

  @override
  _i2.Future<R> run<R>(
    _i2.Future<R> Function(_i3.Session)? fn, {
    _i3.SessionSettings? settings,
    L? locality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #run,
          [fn],
          {
            #settings: settings,
            #locality: locality,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #run,
                  [fn],
                  {
                    #settings: settings,
                    #locality: locality,
                  },
                ),
              ),
              (R v) => _i2.Future<R>.value(v),
            ) ??
            _FakeFuture_0<R>(
              this,
              Invocation.method(
                #run,
                [fn],
                {
                  #settings: settings,
                  #locality: locality,
                },
              ),
            ),
      ) as _i2.Future<R>);

  @override
  _i2.Future<R> runTx<R>(
    _i2.Future<R> Function(_i3.TxSession)? fn, {
    _i3.TransactionSettings? settings,
    L? locality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTx,
          [fn],
          {
            #settings: settings,
            #locality: locality,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<R>(
                this,
                Invocation.method(
                  #runTx,
                  [fn],
                  {
                    #settings: settings,
                    #locality: locality,
                  },
                ),
              ),
              (R v) => _i2.Future<R>.value(v),
            ) ??
            _FakeFuture_0<R>(
              this,
              Invocation.method(
                #runTx,
                [fn],
                {
                  #settings: settings,
                  #locality: locality,
                },
              ),
            ),
      ) as _i2.Future<R>);

  @override
  _i2.Future<_i3.Statement> prepare(Object? query) => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [query],
        ),
        returnValue: _i2.Future<_i3.Statement>.value(_FakeStatement_1(
          this,
          Invocation.method(
            #prepare,
            [query],
          ),
        )),
      ) as _i2.Future<_i3.Statement>);

  @override
  _i2.Future<_i3.Result> execute(
    Object? query, {
    Object? parameters,
    bool? ignoreRows = false,
    _i3.QueryMode? queryMode,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [query],
          {
            #parameters: parameters,
            #ignoreRows: ignoreRows,
            #queryMode: queryMode,
            #timeout: timeout,
          },
        ),
        returnValue: _i2.Future<_i3.Result>.value(_FakeResult_2(
          this,
          Invocation.method(
            #execute,
            [query],
            {
              #parameters: parameters,
              #ignoreRows: ignoreRows,
              #queryMode: queryMode,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i2.Future<_i3.Result>);

  @override
  _i2.Future<void> close({bool? force = false}) => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [Result].
///
/// See the documentation for Mockito's code generation for more information.
class MockResult extends _i1.Mock implements _i3.Result {
  MockResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get affectedRows => (super.noSuchMethod(
        Invocation.getter(#affectedRows),
        returnValue: 0,
      ) as int);

  @override
  _i3.ResultSchema get schema => (super.noSuchMethod(
        Invocation.getter(#schema),
        returnValue: _i4.dummyValue<_i3.ResultSchema>(
          this,
          Invocation.getter(#schema),
        ),
      ) as _i3.ResultSchema);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  Iterator<_i3.ResultRow> get iterator => (super.noSuchMethod(
        Invocation.getter(#iterator),
        returnValue: _FakeIterator_3<_i3.ResultRow>(
          this,
          Invocation.getter(#iterator),
        ),
      ) as Iterator<_i3.ResultRow>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  _i3.ResultRow get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.getter(#first),
        ),
      ) as _i3.ResultRow);

  @override
  set first(_i3.ResultRow? element) => super.noSuchMethod(
        Invocation.setter(
          #first,
          element,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ResultRow get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.getter(#last),
        ),
      ) as _i3.ResultRow);

  @override
  set last(_i3.ResultRow? element) => super.noSuchMethod(
        Invocation.setter(
          #last,
          element,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ResultRow get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.getter(#single),
        ),
      ) as _i3.ResultRow);

  @override
  Iterable<_i3.ResultRow> get reversed => (super.noSuchMethod(
        Invocation.getter(#reversed),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  set length(int? newLength) => super.noSuchMethod(
        Invocation.setter(
          #length,
          newLength,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: <R>[],
      ) as List<R>);

  @override
  _i3.ResultRow operator [](int? index) => (super.noSuchMethod(
        Invocation.method(
          #[],
          [index],
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
      ) as _i3.ResultRow);

  @override
  _i3.ResultRow elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
      ) as _i3.ResultRow);

  @override
  Iterable<_i3.ResultRow> followedBy(Iterable<_i3.ResultRow>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #followedBy,
          [other],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  void forEach(void Function(_i3.ResultRow)? action) => super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool contains(Object? element) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [element],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool every(bool Function(_i3.ResultRow)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool any(bool Function(_i3.ResultRow)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.ResultRow firstWhere(
    bool Function(_i3.ResultRow)? test, {
    _i3.ResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i3.ResultRow);

  @override
  _i3.ResultRow lastWhere(
    bool Function(_i3.ResultRow)? test, {
    _i3.ResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i3.ResultRow);

  @override
  _i3.ResultRow singleWhere(
    bool Function(_i3.ResultRow)? test, {
    _i3.ResultRow Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i3.ResultRow);

  @override
  String join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
      ) as String);

  @override
  Iterable<_i3.ResultRow> where(bool Function(_i3.ResultRow)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  Iterable<T> whereType<T>() => (super.noSuchMethod(
        Invocation.method(
          #whereType,
          [],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> map<T>(T Function(_i3.ResultRow)? f) => (super.noSuchMethod(
        Invocation.method(
          #map,
          [f],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i3.ResultRow)? f) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [f],
        ),
        returnValue: <T>[],
      ) as Iterable<T>);

  @override
  _i3.ResultRow reduce(
          _i3.ResultRow Function(
            _i3.ResultRow,
            _i3.ResultRow,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
      ) as _i3.ResultRow);

  @override
  T fold<T>(
    T? initialValue,
    T Function(
      T,
      _i3.ResultRow,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i4.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as T);

  @override
  Iterable<_i3.ResultRow> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  Iterable<_i3.ResultRow> skipWhile(bool Function(_i3.ResultRow)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  Iterable<_i3.ResultRow> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  Iterable<_i3.ResultRow> takeWhile(bool Function(_i3.ResultRow)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  List<_i3.ResultRow> toList({bool? growable = true}) => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
          {#growable: growable},
        ),
        returnValue: <_i3.ResultRow>[],
      ) as List<_i3.ResultRow>);

  @override
  Set<_i3.ResultRow> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: <_i3.ResultRow>{},
      ) as Set<_i3.ResultRow>);

  @override
  void add(_i3.ResultRow? value) => super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAll(Iterable<_i3.ResultRow>? iterable) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [iterable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? element) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [element],
        ),
        returnValue: false,
      ) as bool);

  @override
  void removeWhere(bool Function(_i3.ResultRow)? test) => super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i3.ResultRow)? test) => super.noSuchMethod(
        Invocation.method(
          #retainWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ResultRow removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
      ) as _i3.ResultRow);

  @override
  void sort([Comparator<_i3.ResultRow>? compare]) => super.noSuchMethod(
        Invocation.method(
          #sort,
          [compare],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffle([_i5.Random? random]) => super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [random],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, _i3.ResultRow> asMap() => (super.noSuchMethod(
        Invocation.method(
          #asMap,
          [],
        ),
        returnValue: <int, _i3.ResultRow>{},
      ) as Map<int, _i3.ResultRow>);

  @override
  List<_i3.ResultRow> operator +(List<_i3.ResultRow>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #+,
          [other],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as List<_i3.ResultRow>);

  @override
  List<_i3.ResultRow> sublist(
    int? start, [
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sublist,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as List<_i3.ResultRow>);

  @override
  Iterable<_i3.ResultRow> getRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i3.ResultRow>[],
      ) as Iterable<_i3.ResultRow>);

  @override
  void removeRange(
    int? start,
    int? end,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRange,
          [
            start,
            end,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fillRange(
    int? start,
    int? end, [
    _i3.ResultRow? fillValue,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fillRange,
          [
            start,
            end,
            fillValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<_i3.ResultRow>? iterable, [
    int? skipCount = 0,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setRange,
          [
            start,
            end,
            iterable,
            skipCount,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(
    int? start,
    int? end,
    Iterable<_i3.ResultRow>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #replaceRange,
          [
            start,
            end,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int indexOf(
    Object? element, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int indexWhere(
    bool Function(_i3.ResultRow)? test, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int lastIndexOf(
    Object? element, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  int lastIndexWhere(
    bool Function(_i3.ResultRow)? test, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  void insert(
    int? index,
    _i3.ResultRow? element,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            index,
            element,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ResultRow removeAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAt,
          [index],
        ),
        returnValue: _FakeResultRow_4(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
      ) as _i3.ResultRow);

  @override
  void insertAll(
    int? at,
    Iterable<_i3.ResultRow>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [
            at,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAll(
    int? at,
    Iterable<_i3.ResultRow>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAll,
          [
            at,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void operator []=(
    int? index,
    _i3.ResultRow? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #[]=,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
