/// UTXO Creation Integration Tests via SPV Flow
/// 
/// These tests validate that BitcoinUtxoEntity is correctly created/updated
/// in Isar database when payments are processed through the SPV flow.
/// 
/// Test Cases:
/// 1. Receiver gets BitcoinUtxoEntity created after SPV validation
/// 2. Sender gets BitcoinUtxoEntity marked as spent after sending
/// 3. Sender gets change BitcoinUtxoEntity created after sending
///
/// Uses real testnet transaction data with valid merkle proofs.

import 'dart:async';
import 'dart:io';
import 'dart:typed_data';
import 'package:test/test.dart';
import 'package:dactor/dactor.dart';
import 'package:isar/isar.dart';
import 'package:eventador/eventador.dart';
import 'package:convert/convert.dart';
import 'package:dartsv/dartsv.dart' as dartsv;
import 'package:libspiffy/libspiffy.dart';
import 'package:libspiffy/src/actors/libspiffy_actor_system.dart';
import 'package:libspiffy/src/actors/invoice_messages.dart';
import 'package:libspiffy/src/actors/wallet_messages.dart';
import 'package:libspiffy/src/storage/isar_wallet_storage.dart';
import 'package:libspiffy/src/utils/beef.dart';
import 'package:libspiffy/src/utils/crypto_utils.dart';
import 'p2p_test_helpers.dart';

void main() {
  group('UTXO Creation via SPV Flow Integration Tests', () {
    // Bob's independent LibSpiffy system (receiver)
    late LibSpiffyActorSystem bobLibSpiffy;
    late Isar bobIsar;
    late LocalActorSystem bobActorSystem;
    late Directory bobTestDir;
    late String bobWalletId;
    late String bobDbName;
    
    setUp(() async {
      print('\n--- Setting up Bob (receiver) system ---');
      
      // Initialize Isar core
      await Isar.initializeIsarCore(download: true);
      
      // Create temporary directory for Bob
      bobTestDir = await Directory.systemTemp.createTemp('bob_utxo_test_');
      print('Bob DB: ${bobTestDir.path}');
      
      // Initialize Bob's system
      bobActorSystem = LocalActorSystem(ActorSystemConfig());
      bobDbName = 'bob_utxo_db_${DateTime.now().microsecondsSinceEpoch}';
      bobIsar = await Isar.open(
        [
          ...LibSpiffySchemas.walletSchemas,
          EventEnvelopeSchema,
          SnapshotEnvelopeSchema,
        ],
        directory: bobTestDir.path,
        name: bobDbName,
      );
      
      bobLibSpiffy = LibSpiffyActorSystem();
      await bobLibSpiffy.initialize(
        actorSystem: bobActorSystem,
        isar: bobIsar,
        dataDirectory: bobTestDir.path,
        enableP2P: false,
      );
      
      // Setup test block headers for Bob
      await setupTestHeaders(bobLibSpiffy.walletStorage as IsarWalletStorage);
      
      // Create Bob's wallet
      bobWalletId = 'bob-wallet-${DateTime.now().millisecondsSinceEpoch}';
      await createWallet(
        walletManager: bobLibSpiffy.walletManager,
        actorSystem: bobActorSystem,
        walletId: bobWalletId,
        walletName: 'Bob Wallet',
      );
      
      print('✓ Bob system initialized with wallet: $bobWalletId');
      print('--- Setup complete ---\n');
    });
    
    tearDown(() async {
      print('\n--- Cleanup ---');
      
      await bobLibSpiffy.shutdown();
      
      try {
        await bobTestDir.delete(recursive: true);
      } catch (e) {
        print('Warning: Could not delete test directory: $e');
      }
      
      print('✓ Cleanup complete\n');
    });

    test('BitcoinUtxoEntity is created for receiver after SPV validation', () async {
      print('\n=== STEP 1: Setup - Register real transaction address in Bob\'s wallet ===');
      
      // The real transaction pays to this address (testnet format)
      // Pubkey hash: f82d58dd8487044d8d0879c15a2a3516a425de2a
      final realTxRecipientAddress = 'n49CCQFuncaXbtBoNm39gSP9dvRP2eFFSw';
      
      // First, we need to register this address with Bob's wallet
      // In production, this address would be generated by the wallet
      // For testing with real transaction data, we register the known address
      print('  Registering real transaction address: $realTxRecipientAddress');
      
      // Directly store the address in the database using wallet storage
      final storage = bobLibSpiffy.walletStorage as IsarWalletStorage;
      await storage.upsertAddress(bobWalletId, AddressMetadata(
        address: realTxRecipientAddress,
        scriptType: 'p2pkh',
        derivationIndex: 0,
        isChange: false,
        purpose: 'receive',
        usageCount: 0,
        balance: BigInt.zero,
        createdAt: DateTime.now(),
        isWatched: true,
      ));
      
      print('✓ Address registered in Bob\'s wallet storage');
      
      // Verify address is stored in Bob's database
      await _verifyAddressInDatabase(
        isar: bobIsar,
        walletId: bobWalletId,
        address: realTxRecipientAddress,
      );
      
      print('\n=== STEP 2: Bob creates invoice with the registered address ===');
      
      // Create invoice (for test purposes, we'll manually associate with the known address)
      final bobCreateCompleter = Completer<InvoiceCreatedMessage>();
      final bobCreateReceiver = await bobActorSystem.spawn(
        'bob-create-receiver',
        () => TestReceiverActor<InvoiceCreatedMessage>(bobCreateCompleter),
      );
      
      bobLibSpiffy.invoiceCoordinator.tell(
        CreateInvoiceMessage(
          walletId: bobWalletId,
          amount: BigInt.from(3883936), // Match real transaction amount
          description: 'Payment for UTXO test',
        ),
        sender: bobCreateReceiver,
      );
      
      final bobInvoice = await bobCreateCompleter.future.timeout(Duration(seconds: 5));
      expect(bobInvoice.success, isTrue);
      expect(bobInvoice.addresses.length, equals(1));
      
      final invoiceId = bobInvoice.invoiceId;
      final invoiceAddress = bobInvoice.addresses.first;
      
      print('✓ Bob created invoice: $invoiceId');
      print('  Invoice address (generated): $invoiceAddress');
      print('  Real TX address (registered): $realTxRecipientAddress');
      print('  Amount: ${bobInvoice.amount} satoshis');
      
      // Note: The invoice address won't match the real TX address, but that's OK
      // because we registered the real TX address in the wallet storage
      // The SPV actor will find it via isWalletAddress() fallback
      
      print('\n=== STEP 3: Verify NO UTXOs exist before payment ===');
      
      // Check that Bob has no UTXOs yet
      final initialUtxoCount = await bobIsar.bitcoinUtxoEntitys.count();
      print('  Initial UTXO count: $initialUtxoCount');
      expect(initialUtxoCount, equals(0), reason: 'Bob should have no UTXOs before payment');
      
      print('\n=== STEP 4: Create BEEF from real testnet transaction ===');
      
      // Use real testnet transaction data
      final realTx = _getRealTransaction1();
      final tscProof = _getTscProof1();
      
      // Create BEEF from real data
      final beef = _createBeefFromRealData(realTx, tscProof);
      
      print('✓ Created BEEF from real transaction');
      print('  TXID: ${realTx['txid']}');
      print('  Block height: ${realTx['blockheight']}');
      print('  BEEF size: ${beef.serialize().length} bytes');
      
      // Extract actual recipient address from transaction for verification
      final txHex = realTx['hex'] as String;
      final tx = dartsv.Transaction.fromHex(txHex);
      final actualTxAddress = _extractP2PKHAddress(tx.outputs[0].script);
      print('  Actual TX recipient address: $actualTxAddress');
      print('  Expected (testnet): $realTxRecipientAddress');
      
      print('\n=== STEP 5: Send BEEF to Bob\'s SPV Actor for validation ===');
      
      // IMPORTANT: We send WITHOUT invoice ID to test the isWalletAddress() fallback path
      // The real TX address was registered in the wallet, so isWalletAddress() should find it
      print('  Sending WITHOUT invoice ID to test isWalletAddress() fallback');
      
      // Bob's SPV actor validates the BEEF
      final spvValidationCompleter = Completer<SPVValidationResult>();
      final spvValidationReceiver = await bobActorSystem.spawn(
        'spv-validation-receiver',
        () => TestReceiverActor<SPVValidationResult>(spvValidationCompleter),
      );
      
      bobLibSpiffy.spvActor.tell(
        ReceiveTransactionMessage(
          transactionId: realTx['txid'] as String,
          beef: beef,
          fromCounterparty: 'alice',
          targetWalletId: bobWalletId,
          // NOTE: No invoiceId - this forces fallback to isWalletAddress() check
        ),
        sender: spvValidationReceiver,
      );
      
      final spvResult = await spvValidationCompleter.future.timeout(
        Duration(seconds: 10),
        onTimeout: () => throw TimeoutException('SPV validation timed out'),
      );
      
      print('✓ SPV validation completed');
      print('  Is valid: ${spvResult.isValid}');
      print('  Validation error: ${spvResult.validationError ?? 'none'}');
      print('  Target wallet: ${spvResult.targetWalletId}');
      print('  Spendable UTXOs: ${spvResult.spendableUTXOs.length}');
      print('  Spent UTXOs: ${spvResult.spentUTXOs.length}');
      
      // Log spendable UTXO details
      for (int i = 0; i < spvResult.spendableUTXOs.length; i++) {
        final utxo = spvResult.spendableUTXOs[i];
        print('    UTXO $i: ${utxo['txid']}:${utxo['outputIndex']} - ${utxo['satoshis']} sats to ${utxo['address']}');
      }
      
      expect(spvResult.isValid, isTrue, 
        reason: 'SPV validation should succeed. Error: ${spvResult.validationError}');
      expect(spvResult.targetWalletId, equals(bobWalletId),
        reason: 'Target wallet ID should be preserved');
      
      // CRITICAL ASSERTION: spendableUTXOs should NOT be empty for receiver
      expect(spvResult.spendableUTXOs, isNotEmpty,
        reason: 'Receiver should have spendable UTXOs after valid SPV payment. '
                'If empty, check: 1) invoice address matches TX output address, '
                '2) isWalletAddress() returns true for the address, '
                '3) AddressEntity is stored with correct walletId');
      
      print('\n=== STEP 6: Wait for projection to process events ===');
      
      // Give the projection time to process events
      await Future.delayed(Duration(milliseconds: 1500));
      
      print('\n=== STEP 7: CRITICAL - Verify BitcoinUtxoEntity exists in Isar ===');
      
      // Query Bob's Isar database for UTXOs
      final bobUtxos = await bobIsar.bitcoinUtxoEntitys.where().findAll();
      
      print('  Bob\'s UTXOs after SPV validation:');
      for (final utxo in bobUtxos) {
        print('    - ${utxo.txid}:${utxo.vout} = ${utxo.satoshis} sats');
        print('      Address: ${utxo.address}');
        print('      Status: ${utxo.status}');
        print('      WalletId: ${utxo.walletId}');
      }
      
      // CRITICAL ASSERTION: BitcoinUtxoEntity must exist
      expect(bobUtxos.length, greaterThan(0),
        reason: 'BitcoinUtxoEntity should be created for receiver after SPV validation. '
                'If 0, the bug is in the flow: SPVActor → WalletManagerActor → '
                'ReceiveUTXOCommand → UTXOReceivedEvent → WalletProjection');
      
      // Verify the UTXO matches the expected transaction
      final expectedTxid = realTx['txid'] as String;
      final matchingUtxo = bobUtxos.where((u) => u.txid == expectedTxid).firstOrNull;
      
      expect(matchingUtxo, isNotNull,
        reason: 'Should have UTXO matching transaction $expectedTxid');
      
      if (matchingUtxo != null) {
        expect(matchingUtxo.walletId, equals(bobWalletId),
          reason: 'UTXO should belong to Bob\'s wallet');
        final satoshiValue = BigInt.tryParse(matchingUtxo.satoshis) ?? BigInt.zero;
        expect(satoshiValue, greaterThan(BigInt.zero),
          reason: 'UTXO should have positive satoshi value');
        print('\n✅ SUCCESS: BitcoinUtxoEntity correctly created!');
        print('   TXID: ${matchingUtxo.txid}');
        print('   Vout: ${matchingUtxo.vout}');
        print('   Satoshis: ${matchingUtxo.satoshis}');
        print('   Address: ${matchingUtxo.address}');
        print('   WalletId: ${matchingUtxo.walletId}');
      }
      
      print('\n=== UTXO Creation Test PASSED ===\n');
    });

    test('Transaction recorded correctly with proper isIncoming flag', () async {
      print('\n=== Testing transaction recording with correct flags ===');
      
      // CRITICAL: Register the real transaction's recipient address in Bob's wallet
      // This is necessary because HD wallets generate unique addresses, but our test
      // uses a hardcoded real transaction with a specific recipient address
      const realTxRecipientAddress = 'n49CCQFuncaXbtBoNm39gSP9dvRP2eFFSw';
      
      print('  Registering real transaction address: $realTxRecipientAddress');
      final storage = IsarWalletStorage(bobIsar);
      await storage.upsertAddress(bobWalletId, AddressMetadata(
        address: realTxRecipientAddress,
        scriptType: 'p2pkh',
        derivationIndex: 0,
        isChange: false,
        purpose: 'receive',
        usageCount: 0,
        balance: BigInt.zero,
        createdAt: DateTime.now(),
        isWatched: true,
      ));
      print('✓ Address registered in Bob\'s wallet storage');
      
      // Create and validate BEEF
      final realTx = _getRealTransaction1();
      final tscProof = _getTscProof1();
      final beef = _createBeefFromRealData(realTx, tscProof);
      
      final spvCompleter = Completer<SPVValidationResult>();
      final spvReceiver = await bobActorSystem.spawn(
        'spv-receiver',
        () => TestReceiverActor<SPVValidationResult>(spvCompleter),
      );
      
      // NOTE: Do NOT pass invoiceId - this forces SPV actor to use isWalletAddress() fallback
      // which will find our manually registered address
      bobLibSpiffy.spvActor.tell(
        ReceiveTransactionMessage(
          transactionId: realTx['txid'] as String,
          beef: beef,
          fromCounterparty: 'alice',
          targetWalletId: bobWalletId,
          // invoiceId intentionally omitted to use isWalletAddress() lookup
        ),
        sender: spvReceiver,
      );
      
      await spvCompleter.future.timeout(Duration(seconds: 10));
      
      // Wait for projection
      await Future.delayed(Duration(milliseconds: 1500));
      
      // Verify transaction is recorded with correct flags
      final transactions = await bobIsar.bitcoinTransactionEntitys.where().findAll();
      
      print('  Recorded transactions:');
      for (final tx in transactions) {
        print('    TXID: ${tx.txid}');
        print('    isIncoming: ${tx.isIncoming}');
        print('    isOutgoing: ${tx.isOutgoing}');
        print('    netAmount: ${tx.netAmount}');
        print('    walletId: ${tx.walletId}');
      }
      
      // Find our transaction
      final expectedTxid = realTx['txid'] as String;
      final recordedTx = transactions.where((t) => t.txid == expectedTxid).firstOrNull;
      
      expect(recordedTx, isNotNull, 
        reason: 'Transaction should be recorded in BitcoinTransactionEntity');
      
      if (recordedTx != null) {
        // For receiver, isIncoming should be true
        expect(recordedTx.isIncoming, isTrue,
          reason: 'isIncoming should be true for receiver');
        expect(recordedTx.isOutgoing, isFalse,
          reason: 'isOutgoing should be false for receiver');
        expect(recordedTx.walletId, equals(bobWalletId),
          reason: 'Transaction should be associated with Bob\'s wallet');
        
        // netAmount should be positive for incoming
        final netAmount = BigInt.tryParse(recordedTx.netAmount) ?? BigInt.zero;
        expect(netAmount, greaterThan(BigInt.zero),
          reason: 'netAmount should be positive for incoming transaction');
        
        print('\n✅ Transaction flags correct!');
        print('   isIncoming: ${recordedTx.isIncoming}');
        print('   netAmount: $netAmount sats');
      }
    });
  });
}

// =============================================================================
// Helper Functions
// =============================================================================

/// Verify that an address exists in the database for the given wallet
Future<void> _verifyAddressInDatabase({
  required Isar isar,
  required String walletId,
  required String address,
}) async {
  // Give projection time to persist
  await Future.delayed(Duration(milliseconds: 500));
  
  final addressEntity = await isar.addressEntitys
      .filter()
      .walletIdEqualTo(walletId)
      .addressEqualTo(address)
      .findFirst();
  
  if (addressEntity != null) {
    print('✓ Address verified in database');
    print('  Address: ${addressEntity.address}');
    print('  WalletId: ${addressEntity.walletId}');
  } else {
    print('⚠️ WARNING: Address not found in database!');
    print('  Expected walletId: $walletId');
    print('  Expected address: $address');
    
    // Check if address exists under any walletId
    final anyAddress = await isar.addressEntitys
        .filter()
        .addressEqualTo(address)
        .findFirst();
    
    if (anyAddress != null) {
      print('  Found address under different walletId: ${anyAddress.walletId}');
    }
  }
  
  expect(addressEntity, isNotNull, 
    reason: 'Address $address should exist in database for wallet $walletId');
}

/// Verify UTXO exists in database with expected properties
Future<void> verifyUtxoInDatabase({
  required Isar isar,
  required String walletId,
  required String txid,
  required int vout,
  String? expectedStatus,
  Duration timeout = const Duration(seconds: 5),
}) async {
  final startTime = DateTime.now();
  BitcoinUtxoEntity? utxo;
  
  while (DateTime.now().difference(startTime) < timeout) {
    utxo = await isar.bitcoinUtxoEntitys
        .filter()
        .walletIdEqualTo(walletId)
        .txidEqualTo(txid)
        .voutEqualTo(vout)
        .findFirst();
    
    if (utxo != null) {
      if (expectedStatus == null || utxo.status == expectedStatus) {
        print('✓ UTXO verified: $txid:$vout');
        print('  Status: ${utxo.status}');
        print('  Satoshis: ${utxo.satoshis}');
        return;
      }
    }
    
    await Future.delayed(Duration(milliseconds: 100));
  }
  
  expect(utxo, isNotNull, 
    reason: 'UTXO $txid:$vout should exist for wallet $walletId');
  if (expectedStatus != null && utxo != null) {
    expect(utxo.status, equals(expectedStatus),
      reason: 'UTXO status should be $expectedStatus');
  }
}

/// Real testnet transaction from block 1641074
Map<String, dynamic> _getRealTransaction1() {
  return {
    "txid": "dd6e7547df0fe893a9a19f66f0377eca72fdcd18fd9f6185fde9c91461a8e8a9",
    "hex": "02000000013706d29b641d2061b0b7b22c81ec6a5670104826bee4472a7513619f4fc298df000000006a473044022021fb2500cfd69bf3d7eee8f16d2e1d6d49528dbe23e9105744202bd9e5b5789102204ff801667c156b97e92209c19dce9bbdd955ee35cea7b815cf9e3b0c1b6727174121022036646b3fd79dee41351f727f0a6e10d0e7f98585961bc14e7aadaf5f4b66ab0100000002a0443b00000000001976a914f82d58dd8487044d8d0879c15a2a3516a425de2a88ac96000000000000001976a914f82d58dd8487044d8d0879c15a2a3516a425de2a88ac00000000",
    "blockhash": "00000000cf9e8013b71e0c1c454208ad60a639adba6b6d7fcf6426da1e1efdb2",
    "blockheight": 1641074,
    "blocktime": 1729051303,
    "confirmations": 24454
  };
}

/// TSC merkle proof for transaction 1
Map<String, dynamic> _getTscProof1() {
  return {
    "index": 6,
    "txOrId": "dd6e7547df0fe893a9a19f66f0377eca72fdcd18fd9f6185fde9c91461a8e8a9",
    "target": "00000000cf9e8013b71e0c1c454208ad60a639adba6b6d7fcf6426da1e1efdb2",
    "nodes": [
      "f4d4fc63094d73b31e13da814ec4556865f53c329c53020e56ad71464e6f85fe",
      "bdcde417243f95840bd6fcfddbad0b198285f9f38d38093dc8826c3a3a7666f0",
      "9304304659a72e3e17ad1a447fecb4b082c8340683249a2cfa8ea3d411ad5c76",
      "5d2528dae0d0992da93f485ccbef24f06ef62ebf055bcc9d43b05dbdbe897dc2"
    ]
  };
}

/// Create BEEF from real transaction and merkle proof
BEEF _createBeefFromRealData(Map<String, dynamic> tx, Map<String, dynamic> tscProof) {
  final txHex = tx['hex'] as String;
  final txBytes = Uint8List.fromList(hex.decode(txHex));
  final blockHeight = tx['blockheight'] as int;
  
  // Create BUMP from TSC proof
  final bump = CryptoUtils.createBumpFromTscProof(tscProof, blockHeight);
  
  return BEEF.create(
    bumps: [bump],
    txs: [txBytes],
    hasMerkle: [true],
    bumpIndex: [0],
  );
}

/// Extract P2PKH address from script
String _extractP2PKHAddress(dartsv.SVScript script) {
  final locker = dartsv.P2PKHLockBuilder.fromScript(script);
  return locker.address?.toBase58() ?? 'unknown';
}
